### ISSUE TITLE
Use tags

### ISSUE THREAD

**Issue by gabrielkoerich** [pagarme/pagarme-php#10]
I think it is really dangerous to use "dev-master" as a composer requirement on my production environment. 

Can you create a tag?

Thanks =)

**Comment by arthurprogramming** [comment]
Please, create tags.

**Comment by chrisenytc** [comment]
I think this is possible. I will create soon as possible. Thank for your suggestion. :+1:

**Comment by hugofcampos** [comment]
:+1:

**Comment by bycosta** [comment]
IMHO the time you spent answering this issue is the time you will spend creating a tag and pushing it.

$ git tag -a 1.0.0 -m 'Initial release'
$ git push origin 1.0.0

**Comment by hugofcampos** [comment]
You can use this fork: https://github.com/hugofcampos/pagarme-php

**Comment by danielcosta** [comment]
@pedrofranceschi @hdubugras @greenboxal @jgabrielfaria @thebergamo could you please create a tag to start versioning here?

**Comment by chrisenytc** [comment]
Done

**Comment by bycosta** [comment]
Great, thanks! Now could you update packagist to reflect the new version?

https://packagist.org/about#how-to-update-packages

**Comment by arthurprogramming** [comment]
Update packagist too, please.
