### ISSUE TITLE
Alteração de pacote para composer

### ISSUE THREAD

**Issue by rdehnhardt** [pagarme/pagarme-php#11]
Seria um grande diferencial para o pacote de integração estar em formato do composer, assim poderia ser incluido mais facilmente em Frameworks que trabalham com o composer!

Atualmente existem muitos Frameworks utilizando: Laravel, Synfony, Zend 2 entre outros.

**Comment by bycosta** [comment]
Agora pra ficar completo, falta criar uma tag (release), pois todo composer install ele faz o clone de novo! E quando tem tag ele faz cache...

**Comment by hugofcampos** [comment]
:+1:

**Comment by regisnew** [comment]
já tem tag
