### ISSUE TITLE
boleto_url e boleto_barcode

### ISSUE THREAD

**Issue by jonathanribas** [pagarme/pagarme-php#116]
**Versão:** 3.0.1
https://github.com/pagarme/pagarme-php/tree/V3/

Ao rodar o código abaixo não estou conseguindo recuperar o "boleto_url" e "boleto_barcode" porem o pedido aparece corretamente lá no Dashboard, parece que os getters estão faltando na classe BoletoTransaction.

`$this->pagarMe = new PagarMe($apiKey);`

`$transaction = $this->pagarMe->transaction()->boletoTransaction($amount, $customer, $this->helper->getNotificationUrl());`

**Comment by devdrops** [comment]
Olá @jonathanribas!

Muito obrigado pela sua observação. Estamos analisando o impacto da exposição dos valores, que parece sim muito benéfico para a funcionalidade de boletos. Vamos atualizando esta issue para te colocar a par do que concluirmos aqui, ok?
