### ISSUE TITLE
Problema na busca de transação

### ISSUE THREAD

**Issue by jonathanribas** [pagarme/pagarme-php#117]
Versão: 3.0.1
https://github.com/pagarme/pagarme-php/tree/V3/

A busca de transação (transactionId) não está funcionando corretamente pois a busca só aceita dígitos porém no ambiente de homologação temos transações do tipo "test_transaction_SltLsBdOI6GYCPexmfKqJllShSfwME".

**Comment by devdrops** [comment]
Com o merge de #118, a correção desta issue foi realizada.
