### ISSUE TITLE
Arrays como argumentos para construção de objetos

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-php#120]
#### Contexto

Hoje, para realizar uma transação, temos 2 formas distintas para compor um objeto `\PagarMe\Sdk\Customer\Customer`:

- Através da API, usando `\PagarMe\Sdk\Customer\CustomerHandler->get()`, que nos retorna uma estrutura de objetos completa;
- Através do construtor, passando os dados como um array, onde as estruturas de Address e Phone são arrays dentro de Customer.

#### O Problema

A classe `\PagarMe\Sdk\Transaction\Request\TransactionCreate` sofreu alterações para esse problema, gerando instâncias de Address e Phone caso esses dados sejam arrays ao invés de objetos.

[\PagarMe\Sdk\Transaction\Request\TransactionCreate](https://github.com/pagarme/pagarme-php/blob/V3/lib/Transaction/Request/TransactionCreate.php#L24)
```php
/**
 * @return array
 */
 public function getPayload()
 {
    $customer = $this->transaction->getCustomer();

    $address = $customer->getAddress();
    if (is_array($address)) {
        $address = new \PagarMe\Sdk\Customer\Address($address);
    }
    $phone = $customer->getPhone();
    if (is_array($phone)) {
        $phone = new \PagarMe\Sdk\Customer\Phone($phone);
    }
```

Para que isso seja resolvido, precisamos encontrar uma forma mais limpa e consistente para manipulação desses dados, cogitando manter as duas interfaces de entrada de dados (array e objeto) ou mantendo somente uma (objeto).

**Comment by pedrocasado** [comment]
Inclusive, o object Customer deveria ser opcional, já que a API aceita para os casos sem ClearSale.

**Comment by leonampd** [comment]
@devdrops considero que esse problema foi/está resolvido na nova versão 4 do SDK. Vou fechar essa issue mas se achar que não faz sentido fique à vontade para reabrir. :wink:
