### ISSUE TITLE
Retorno da criação e assinatura

### ISSUE THREAD

**Issue by dcheloni** [pagarme/pagarme-php#121]
Estou utilizando o branch master (v2) e estou com problema ao criar uma assinatura, pois não tenho retorno dos dados após a assinatura criada, assim como acontece na criação do plano. Poderiam ter colocado na documentação o retorno das requisições.

**Comment by devdrops** [comment]
Oi @dcheloni!

No presente momento, a versão `v2` se encontra depreciada e infelizmente sem uma documentação concisa. Entretanto, entregamos a versão `v3` com exemplos e documentação completa (aqui na [wiki deste repositório](https://github.com/pagarme/pagarme-php/wiki)). Recomendamos que siga com a versão `v3`, que contém mais conteúdo, mais documentação e recursos da nossa API.

**Comment by dcheloni** [comment]
Importei a api v3 no meu projeto e já estou com um problema ao setar a apiKey: Class 'PagarMe\Sdk\Client' not found in PagarMe.php on line 134

**Comment by devdrops** [comment]
Olá @dcheloni!

Peço que mantenha os assuntos em issues separadas, seguindo nosso [guia de contribuição ](https://github.com/pagarme/pagarme-php/blob/V3/CONTRIBUTING.md), ao invés de alterar uma issue já existente, para manter o histórico da solução do seu problema para outras pessoas :wink:. Por favor, siga os seguintes passos:

1. Encerre esta issue, caso o problema inicial se encontre resolvido.
2. Abra uma outra issue para podermos seguir com a discussão nela.
