### ISSUE TITLE
Problema ao setar a apiKey

### ISSUE THREAD

**Issue by dcheloni** [pagarme/pagarme-php#122]
Importei a api v3 no meu projeto e já estou com um problema ao setar a apiKey: Class 'PagarMe\Sdk\Client' not found in PagarMe.php on line 134

**Comment by devdrops** [comment]
Oi @dcheloni!

Parece que a classe de Client do nosso SDK não foi devidamente carregada. Sugiro verificar:

- Como instalou a versão V3 (instruções [aqui](https://github.com/pagarme/pagarme-php/blob/V3/README.md));
- Autoloader do seu projeto, para validar se as classes estão sendo corretamente carregadas.

No aguardo do seu retorno.

**Comment by dcheloni** [comment]
Não tinha instalado a api corretamente, instalei novamente pelo composer e deu tudo certo.

**Comment by devdrops** [comment]
Muito obrigado pelo feedback @dcheloni!
