### ISSUE TITLE
Problemas ao usar Address e Phone como objetos

### ISSUE THREAD

**Issue by gabrielalan** [pagarme/pagarme-php#123]
Olá,

Estou tentando usar a API do PagarMe, como ensinado na documentação aqui (aliás, a documentação básica está aparentemente errada, já que usando Composer, não consigo seguir os passos daqui: https://docs.pagar.me/transactions/).

Entretanto, ao criar um Address e Phone, passando para o Customer e tentando criar uma transação acontece o seguinte erro: `Cannot use object of type PagarMe\Sdk\Customer\Address as array in C:\Projects\pagarmetest\vendor\pagarme\pagarme-php\lib\Transaction\Request\TransactionCreate.php`.

O erro é meio óbvio pois olhando o código é simples de corrigir aparentemente: 
```php
<?php
 'address' => [
    'street'        => $address['street'],
    'street_number' => $address['street_number'],
    'complementary' => isset($address['complementary']) ? $address['complementary']: null,
    'neighborhood'  => $address['neighborhood'],
    'zipcode'       => $address['zipcode']
]
```

Como podem ver, o código está tentando utilizar o $address como se fosse um array, mas ele é uma instância de `\PagarMe\Sdk\Customer\Address`.

Alterando para (por exemplo) $address->getAddress(), já corrige o problema, mas eu realmente não sei por que este código foi escrito assim.

Alguma coisa que preciso fazer?
O código inteiro é este: 

```php
<?php
$pagarMe = new PagarMe("xxx");

$card = $pagarMe->card()->create('xxx', 'JOHN DOVE', '0722');

$address = new \PagarMe\Sdk\Customer\Address([
	'street' => 'xxx',
	'streetNumber' => 'xx',
	'neighborhood' => 'xxx',
	'zipcode' => 'xxx',
	'complementary' => '',
	'city' => 'xxx',
	'state' => 'xxx',
	'country' => 'xxx',
]);

$phone = new \PagarMe\Sdk\Customer\Phone(['ddd' => '47', 'number' => '99999999', 'ddi' => '55']);

$customer = $pagarMe->customer()->create(
	'John Dove',
	'john@site.com',
	'09130141095',
	$address,
	$phone,
	'15021994',
	'M'
);

$transaction = $pagarMe->transaction()->creditCardTransaction(
	1000,
	$card,
	$customer,
	1,
	true,
	'http://requestb.in/pkt7pgpk',
	['idProduto' => 13933139]
);
```

Ps.: **Esse código é só um exemplo que estou tentando fazer pois estou apenas testando a API para uso posterior**

**Comment by devdrops** [comment]
Olá @gabrielalan, boa tarde!

Muito obrigado pelo seu feedback. Vamos às suas dúvidas:

> Estou tentando usar a API do PagarMe, como ensinado na documentação aqui (aliás, a documentação básica está aparentemente errada, já que usando Composer, não consigo seguir os passos daqui: https://docs.pagar.me/transactions/).

Estamos trabalhando para atualizar essa documentação. No momento, use como referência a [documentação feita para a versão V3 deste SDK](https://github.com/pagarme/pagarme-php/wiki).

> Alguma coisa que preciso fazer?

A correção para esse bug foi realizada na [tag v3.0.2](https://github.com/pagarme/pagarme-php/releases/tag/v3.0.2). Por favor, verifique no Packagist a disponibilidade dessa versão para manter o SDK atualizado em seus projetos.

**Comment by gabrielalan** [comment]
Pelo que vi no Packagist só existe até a versão 3.0.1, e as versões dev e dev-master, que preferia não usar.

**Comment by devdrops** [comment]
@gabrielalan de fato, as versões mais antigas se encontram depreciadas. Somente recomendamos o uso das versões em master para cenários com PHP <= 5.3.*.

Sobre o Packagist: estamos trabalhando para entender porque o webhook do Packagist não atualizou a referência. Assim que tivermos o update da tag, podemos atualizar a situação nesta mesma issue.

**Comment by xduh** [comment]
@gabrielalan Corrigimos nossa integração com o Packagist, a versão 3.0.2 já consta lá, tente atualizar suas dependências por favor.

**Comment by devdrops** [comment]
Fala @gabrielalan!

Poderia por favor validar sua atualização do nosso módulo? Assim, caso o problema tenha se resolvido, fecharemos a issue concluindo a correção.

**Comment by gabrielalan** [comment]
Olá @devdrops,

Estou viajando no momento, mas assim que chegar verifico. Obrigado.

**Comment by devdrops** [comment]
@gabrielalan certo, ficamos no aguardo do teu feedback disso ok?

**Comment by devdrops** [comment]
@gabrielalan estamos fechando a issue pois a solução já foi adicionada no SDK. Caso necessário, reabra a issue ou por favor, notifique-nos em caso de qualquer dúvida :wink:
