### ISSUE TITLE
Criação de assinatura com card hash

### ISSUE THREAD

**Issue by dcheloni** [pagarme/pagarme-php#126]
Não encontrei na v3 opção de criar uma assinatura utilizando o card hash ou criar um cartão utilizando o card hash.

**Comment by danielok1303** [comment]
Também estou com o mesmo problema, alguém dá um help aqui?

**Comment by petriuslima** [comment]
Bom dia @dcheloni e @danielok1303.

Essa funcionalidade está disponível na release v3.1.0. Ela já se encontra disponível no packagist inclusive.

Para utilizá-la, basta criar o cartão utilizando o `card_hash` e passar esse cartão para a assinatura. Conforme abaixo:

```php
$card = new \PagarMe\Sdk\Card\Card(['hash' => $card_hash]);

$pagarMe->subscription()->createCardSubscription(
    $plan, $card, $customer
);
```

**Comment by dcheloni** [comment]
Baixei a nova release da api mas ainda não consegui criar a assinatura utilizando o card_hash.
Utilizei conforme mencionado acima, criando o cartão sem utilizar o card_hash funcionou, porém utilizando os mesmos dados para gerar o card_hash não retornou nenhum resultado.

Ao criar o cartão utilizando o hash, só foi retornado o hash, o id e todas outras propriedades vieram vazias, está correto isso?

**Comment by petriuslima** [comment]
@dcheloni, o exemplo acima retorna o objeto subscrition, acabei não deixando no exemplo e peço desculpas. :worried: 
O correto seria uma variável para receber o objeto, tal como:
```php
$subscription = $pagarMe->subscription()->createCardSubscription(
    $plan, $card, $customer
);
```

Mesmo que algum problema ocorra, ele deveria lançar uma `ClientException` com a descrição do problema que houve na API, apareceu algo mais pra você?

> Ao criar o cartão utilizando o hash, só foi retornado o hash, o id e todas outras propriedades vieram vazias, está correto isso?

Sim, está correto. No `card_hash` estão todas as informações necessárias do cartão e caso houvesse o `id` do cartão, não haveria necessidade de passar o `card_hash`.

**Comment by dcheloni** [comment]
Sempre retorna esse erro.
`error : {
		type : invalid_parameter,
		parameter_name : card_hash,
		message : card_hash inválido
	}`
OBS.: Criei o cartão da forma normal, utilizando cardNumber, holderName e cardExpirationDate e funcionou normalmente, utilizei os mesmos dados para criar o card_hash e sempre retorna esse erro.

**Comment by petriuslima** [comment]
@dcheloni pode me passar a data de expiração e a bandeira do cartão utilizado?

**Comment by dcheloni** [comment]
Visa - 12/30

**Comment by petriuslima** [comment]
@dcheloni Existem números de cartões de crédito excluisivos para testes. Existem diversos sites onde você pode gerá-los.

**Comment by dcheloni** [comment]
Estou utilizando esses cartões mesmo para teste, porém sem sucesso ao tentar criar assinatura utilizando o card_hash.

**Comment by petriuslima** [comment]
@dcheloni Testei aqui gerando o `card_hash` mas a assinatura foi criada normalmente. Os dados que eu utilizei para gerar o `card_hash` seguem abaixo (cartão de teste gerado [aqui](http://www.geradorcartaodecredito.com.br/visa)):
```php
$card = [
    'card_number' => '4916521680166972',
    'card_holder_name' => 'Usuario de Teste',
    'card_expiration_date' => '1230',
    'card_cvv' => '123'
];
```
Uma ressalva importante é que se você estiver gerando o `card_hash` manualmente, o valor da propriedade `card_expiration_date` não pode conter barra. Ou seja, o formato deve ser `MMYY` (M = mês e Y = ano).

Como você está gerando os dados para compor o `card_hash`? Acredito que nosso problema pode estar nessas informações de entrada ou em alguma outra dependência utilizada em seu projeto.

**Comment by petriuslima** [comment]
@dcheloni Conseguiu criar a assinatura?

**Comment by dcheloni** [comment]
Não consegui criar a assinatura ainda, estou gerando o card_hash pelo tutorial que está no link: https://docs.pagar.me/capturing-card-data/#capturando-os-dados-em-uma-pagina-web

**Comment by dcheloni** [comment]
Consegui criar assinatura, realmente era algum erro na forma de eu capturar os dados para gerar o card_hash. Muito obrigado!
