### ISSUE TITLE
Transação de boletos com problemas devido a propriedades não declaradas.

### ISSUE THREAD

**Issue by rorteg** [pagarme/pagarme-php#128]
Versão 3.0

Ao executar o método implementado e referenciado na issue: #116

[`public function getBoletoUrl()
    {
        return $this->boletoUrl;
    }`](https://github.com/pagarme/pagarme-php/blob/V3/lib/Transaction/BoletoTransaction.php#L36)
[`public function getBoletoBarcode()
    {
        return $this->boletoBarcode;
    }`](https://github.com/pagarme/pagarme-php/blob/V3/lib/Transaction/BoletoTransaction.php#L45)

Está retornando erros, pois a propriedade boletoUrl e boletoBarcode não existem no objeto em questão.

Isto acontece por conta do método fill da trait Fillable implementada na class AbstractTransaction: [fill()](https://github.com/pagarme/pagarme-php/blob/V3/lib/Fillable.php#L12)

Este método checa se a propriedade existe antes de setar como field do objeto.

**Comment by devdrops** [comment]
Olá @rorteg!

Para fins de histórico, poderia postar aqui os erros que ocorrem nesse processo?

**Comment by rorteg** [comment]
Olá @devdrops !

A transação do boleto estava sendo criada do lado Pagarme, e na response vinha os dados corretos, somente mascarei alguns campos com (x) para postar aqui:

```
{
   "Response":{
      "object":"transaction",
      "status":"waiting_payment",
      "refuse_reason":null,
      "status_reason":"acquirer",
      "acquirer_response_code":null,
      "acquirer_name":"pagarme",
      "acquirer_id":"xxxxxx",
      "authorization_code":null,
      "soft_descriptor":null,
      "tid":xxxx,
      "nsu":xxxx,
      "date_created":"2017-02-21T14:49:08.199Z",
      "date_updated":"2017-02-21T14:49:08.451Z",
      "amount":100,
      "authorized_amount":100,
      "paid_amount":0,
      "refunded_amount":0,
      "installments":1,
      "id":xxxx,
      "cost":0,
      "card_holder_name":null,
      "card_last_digits":null,
      "card_first_digits":null,
      "card_brand":null,
      "card_pin_mode":null,
      "postback_url":"http:\/\/xxx.dev\/ue_pagarme\/notification\/transaction\/",
      "payment_method":"boleto",
      "capture_method":"ecommerce",
      "antifraud_score":null,
      "boleto_url":"https:\/\/pagar.me",
      "boleto_barcode":"1234 5678",
      "boleto_expiration_date":"2017-02-28T03:00:00.000Z",
      "referer":"api_key",
      "ip":"xxxx",
      "subscription_id":null,
      "phone":{
         "object":"phone",
         "ddi":"55",
         "ddd":"xx",
         "number":"xxxxxxxxxx",
         "id":xxxx
      },
      "address":{
         "object":"address",
         "street":"xxxxx",
         "complementary":"",
         "street_number":"xxx",
         "neighborhood":"xxxxxx",
         "city":"xxxxx",
         "state":"PR",
         "zipcode":"xxxxxxxxx",
         "country":"Brasil",
         "id":xxxxx
      },
      "customer":{
         "object":"customer",
         "document_number":"xxxxxxx",
         "document_type":"cpf",
         "name":"xxxxxxx",
         "email":"xxxxx@xxxxxx.com.br",
         "born_at":null,
         "gender":null,
         "date_created":"2017-02-21T03:55:46.462Z",
         "id":154237
      },
      "card":null,
      "split_rules":null,
      "metadata":{

      },
      "antifraud_metadata":{

      }
   }
}
```

Como pode ver, todos os dados estão vindo na response corretamente.

O problema é quando em nosso projeto (consumidor do SDK), tentamos recuperar a URL do boleto e o Barcode:

```
$transaction = $this->pagarMe->transaction()->boletoTransaction(
            $amountInCents,
            $customer,
            $this->helper->getNotificationUrl(),
            null,
            [
                'postbackUrl' => $this->helper->getNotificationUrl(),
                'boleto_expiration_date' => $date->format('Y-m-d\TH:i:m')
            ]
      );

$boletoUrl = $transaction->getBoletoUrl(); // Aqui o erro acontece, pois este método retorna ($this->boletoUrl) o qual não foi setado na classe.

$boletoBarcode = $transaction->getBoletoBarcode(); // Aqui o erro acontece, pois este método retorna ($this->boletoBarcode) o qual não foi setado na classe.
```

Em meu sistema é lançada uma exception com um Notice:
Notice: Undefined property: PagarMe\Sdk\Transaction\BoletoTransaction::$boletoUrl in /home/cloudpanel/htdocs/xxx/vendor/pagarme/pagarme-php/lib/Transaction/BoletoTransaction.php on line 38

Como havia explicado na abertura da Issue, isto está ocorrendo pelo fato de o método fill não setar no objeto as propriedades boletoUrl e boletoBarcode, pois estas propriedades não estão declaradas na classe e não passam pela condicional:

```
if (property_exists($this, $field)) {
       $this->$field = $value;
}
```

Os métodos getBoletoUrl e getBoletoBarcode retornam o erro de Undefined.

Abraços

**Comment by devdrops** [comment]
@rorteg muito obrigado pelo excelente feedback!

**Comment by devdrops** [comment]
@rorteg correção aceita e mergeada em #129 :wink:, mais uma vez muito obrigado!

**Comment by rorteg** [comment]
@devdrops Obrigado vocês pelas respostas rápidas, assim conseguimos seguir com nosso fluxo interno.

Abraços ;)

**Comment by rorteg** [comment]
@devdrops ,

Chegaram a fazer o update na parte do Packgist?
Preciso especificar uma versão em específico em minhas dependências?

Temos declarado dessa forma, porém não está trazendo essas atualizações:
"pagarme/pagarme-php": "^3.0"

Abraços

**Comment by devdrops** [comment]
@rorteg vamos subir uma nova tag, assim o packagist será atualizado. Aviso aqui assim que a gente subir essa tag, ok?

**Comment by rorteg** [comment]
Obrigado @devdrops .

Ok.

**Comment by devdrops** [comment]
@rorteg feito, tag disponível no packagist! Pode por favor conferir a instalação?

**Comment by rorteg** [comment]
Tudo certinho agora @devdrops . 
Muito obrigado.
