### ISSUE TITLE
SDK trata endereços e telefones de forma diferente da API

### ISSUE THREAD

**Issue by petriuslima** [pagarme/pagarme-php#130]
Pelo que foi analisado no seguinte trecho de código:
```php
$customerData->address = new Address(
    get_object_vars($customerData->addresses[0])
);

$customerData->phone = new Phone($customerData->phones[0]);
```

A SDK está tratando os dados como um único objeto para `Address` e para `Phone` e a API utiliza um array de objetos.

**Comment by devdrops** [comment]
Problema relacionado em #120.

**Comment by ricardotulio** [comment]
@devdrops não é o mesmo problema. A issue #120 fala sobre arrays espalhados pela SDK como se fossem objetos, e esse se trata de como `customer` se relaciona com `address` e `phone`. Hoje no SDK está 1 para 1, enquanto na API aparentemente é 1 para n.

**Comment by leonampd** [comment]
@petriuslima vou fechar essa issue dado que recentemente lançamos uma versão nova do SDK que não tem esse problema, ok?
