### ISSUE TITLE
[NFR] Ability to fetch the payables from a given transaction

### ISSUE THREAD

**Issue by williamokano** [pagarme/pagarme-php#131]
I was looking into the pagar.me docs and I noticed that on the payables endpoint it is possible to fetch a list of payables using any property as filter.

Said that, I need the ability to fetch those payables with the SDK V3. I know that it's possible to fetch it using the elasticsearch advanced search, but I think it could be a good idea to have an specific method (under payables domain) to get those data and not using the elastic search stuff.

**Comment by devdrops** [comment]
Hih @williamokano! Do you still have something in mind for this issue?

**Comment by williamokano** [comment]
HI @devdrops I don't. Since I have to count has many payables by fetching the transaction (which will have to make 2 requests, making the performance for this action pretty bad. I think that is for the best if we drop this feature and start a new one, but, instead of fetching all the payables for some given transaction, create a new method with the possibility to pass the `count` and the `page` argument and let the user handle how to fetch those data.

**Comment by topogigiovanni** [comment]
Hello everyone, sorry for the intrusion, but it would make sense to give TransactionHandler the ability to query your Payables ([doc](https://docs.pagar.me/api/?shell#retornando-transaction-payments)) so you don't need the Paging Parameters ? In this case, we would not have the restriction of 10 results, but from what I've noticed, it skips some of the list result patterns (which contains page and count).

Thank you guys.

**Comment by williamokano** [comment]
Hi @topogigiovanni.

Have you tried the elastic search advanced query? I think that might solve our problem hehehe.

**Comment by topogigiovanni** [comment]
It's a good alternative, sure, but I thought I'd create a shortcut to this feature. In my project I am using this feature a lot.

Anyway thanks for the attention @williamokano 

Cheers.

**Comment by williamokano** [comment]
What kind of query you need in the TransactionHandler? I am using this feature a lot too, since I have to keep track of the payables in order to build some custom bulk anticipations. But in my case, I just need to query the payables for some specific given transaction. The query for transaction_id works, but I don't actually know how many payables I don't know exactly how many payables the given transaction has, I have to keep scraping all the pages.

I suggested the elasticsearch since it's a good alternative for me, I thought it might solve your problem too :)

**Comment by topogigiovanni** [comment]
In fact it would only be for a match to the existing method in the API ([link](https://docs.pagar.me/api/?shell#retornando-um-pagamento-da-transacao)). Of course, elasticsearch works very well, but by looking closely at the PHP SDK I've missed the coverage of this feature, given the importance of the Payable entity.

Thanks again @williamokano , elasticsearch is really amazing and your solution will work perfectly for me. :)

**Comment by devdrops** [comment]
Hi @williamokano and @topogigiovanni!

We believe that this issue is solved, so we're closing it, and if you guys still need to discuss it further, please feel free to reopen it :wink:
