### ISSUE TITLE
[Question] SDK V3 Payable object don't have recipient_id

### ISSUE THREAD

**Issue by williamokano** [pagarme/pagarme-php#134]
Digging into the SDK and the api documentation (https://docs.pagar.me/api/#objeto-payable) I noticed that there's no mention about the `recipient_id` on the `Payable` return object.

I checked on the api and it return this info. Follow the object that I got from the api call:

```json
[{
    "object": "payable",
    "id": 107xxxxx,
    "status": "waiting_funds",
    "amount": 6492,
    "fee": 0,
    "anticipation_fee": 0,
    "installment": 12,
    "transaction_id": 132xxxx,
    "split_rule_id": "sr_cizhajmq400c5zg6e0xxxxxxx",
    "bulk_anticipation_id": null,
    "recipient_id": "re_ciy67slew0220kn6evxxxxxxx",
    "payment_date": "2018-02-20T03:00:00.000Z",
    "original_payment_date": null,
    "type": "credit",
    "payment_method": "credit_card",
    "date_created": "2017-02-22T18:28:23.527Z"
}]
```

_PS.:_ I added some `x` characters into the `id`, `transaction_id`, `split_rule_id` and `recipient_id` to "hide" the original data.

There's any intention in adding this on the SDK? Is the documentation incomplete yet?

Thanks in advance.

**Comment by devdrops** [comment]
Favor seguir a formatação original para issues, conforme [modelo](https://github.com/pagarme/pagarme-php/blob/V3/.github/ISSUE_TEMPLATE.md).

**Comment by devdrops** [comment]
Oi @williamokano!

Pela necessidade de seguir um padrão para report de issues, solicitamos que seja seguido o formato que propomos, conforme [modelo](https://github.com/pagarme/pagarme-php/blob/V3/.github/ISSUE_TEMPLATE.md).

Como o padrão não foi seguido, vamos fechar esta issue. Caso tenha necessidade de seguir com o assunto, peço que edite o formato e reabra esta mesma issue. Ou caso preferir, pode abrir um pull requetst com as alterações necessárias.
