### ISSUE TITLE
Split Rules em transação com cartão de crédito

### ISSUE THREAD

**Issue by spportz** [pagarme/pagarme-php#136]
Como faço para utilizar as regras de split nas transações utilizando cartão de crédito? O código abaixo está ignorando as informações de "split_rules"

```
$pagarme->transaction()->creditCardTransaction(
         intval($itemPrice*100),
         $card,
         $customer,
         1,
          true,
          null,
          ['item' => $itemName],
          [
                'split_rules' => array(
                       array(
                            'recipient_id' => 're_cizsf7yqb00nefv6esyivk11k',
                            'charge_processing_fee' => false,
                            'liable' => true,
                            'percentage' => '80',
                        ),
                        array(
                            'recipient_id' => 're_cizk96xvh049bws6ey9wf92tq',
                            'charge_processing_fee' => true,
                            'liable' => false,
                            'percentage' => '20',
                 )
           )
     ]
);
```

**Comment by xduh** [comment]
@spportz o conteúdo de 'split_rule' deve ser um objeto 'PagarMe\Sdk\SplitRule\SplitRuleCollection', contendo objetos  'PagarMe\Sdk\SplitRule\SplitRule', que podem ser criados manualmente ou com o handler de splitRule.
https://github.com/pagarme/pagarme-php/wiki/Regras-do-Split

**Comment by mandelaloko** [comment]
@xduh na documentação não mostra que o recipient tem que ser enviado como meta.

**Comment by xduh** [comment]
@mandelaloko o recipient não deve ser passado no metadata, e sim dentro de um objeto `PagarMe\Sdk\SplitRule\SplitRule`.

**Comment by spportz** [comment]
@xduh de acordo com o que você falou, reescrevi o código e, enfim, deu tudo certo! Deixo abaixo o código correto:

```
$sppRecipient = new Recipient(['id' => 're_cizk96xvh049bws6ey9wf92tq']);
$ptnRecipient = new Recipient(['id' => 're_cizsf7yqb00nefv6esyivk11k']);

$sppSplit = new SplitRuleHandler();
$sppSplit = $sppSplit->percentageRule(10, $sppRecipient, true, false);

$ptnSplit = new SplitRuleHandler();
$ptnSplit = $ptnSplit->percentageRule(90, $ptnRecipient, true, true);

$splitRules = new SplitRuleCollection();
$splitRules->offsetSet(0, $ptnSplit);
$splitRules->offsetSet(1, $sppSplit);

$transaction = $gateway->transaction()->creditCardTransaction(
      intval($itemPrice*100),
      $card,
      $customer,
      1,
      true,
      null,
      ['item' => $itemName],
      ['split_rules' => $splitRules]
);
```

**Comment by xduh** [comment]
Show @spportz :+1:

**Comment by mandelaloko** [comment]
@xduh estou usando o \PagarMe\Sdk e não consegui estanciar a SplitRuleCollection, consegue me dar um help?

Estou fazendo assim:

`
         $this->api 	= new \PagarMe\Sdk\PagarMe('ak_test_NDzSNhQbNCx8JCVxcuY3NxvbBopzdf');
        $recipients     = $this->api->recipient()->getList();
        $arrayRecipient = array();
        foreach ($recipients as $recipient) {
            if ( ! $this->existRecipientInBankAccount($recipient->getbankAccount()->getconta())) continue;

            $percent  = $this->getPercentageByBankAccount($recipient->getbankAccount()->getconta());
            $arrayRecipient[] = $this->api->splitRule()->percentageRule(
                $percent,
                $recipient,
                true,
                true
            );
        }
        return $arrayRecipient;
`

**Comment by xduh** [comment]
@mandelaloko sua variável: `$arrayRecipient` deveria ser na verdade um objeto `PagarMe\Sdk\SplitRule\SplitRuleCollection`. Da uma olhada no exemplo acima deixado pelo @spportz
