### ISSUE TITLE
postbackUrl null ao criar assinatura com card_hash

### ISSUE THREAD

**Issue by dcheloni** [pagarme/pagarme-php#137]
Ao criar uma assinatura utilizando o card_hash (release 3.1.0), o postbackUrl não é salvo, ficando sempre null.

**Comment by petriuslima** [comment]
Olá @dcheloni. Muito obrigado por nos informar sobre esse problema. A PR para solucionar isso já foi criada. :+1:

**Comment by petriuslima** [comment]
@dcheloni, release liberada no packagist! :+1:
