### ISSUE TITLE
Criar transação sem dados do customer

### ISSUE THREAD

**Issue by henriquekano** [pagarme/pagarme-php#138]
* Problema: Criar uma transação sem dados do customer
 * Tentativas:
```php
<?php
require __DIR__.'/vendor/autoload.php';

date_default_timezone_set('America/Sao_Paulo');
$pagarMe = new \PagarMe\Sdk\PagarMe('API_KEY');

$card = new \PagarMe\Sdk\Card\Card([
    'id' => 'card_cizri9czn00csfi6e1ygzw9vz',
    'cvv' => '122'
]);

//tentativa 1
$customer = new \PagarMe\Sdk\Customer\Customer(
    [
        'address' => new \PagarMe\Sdk\Customer\Address([]),
        'phone' => new  \PagarMe\Sdk\Customer\Phone([])
    ]
);
//tentativa 2
$customer = new \PagarMe\Sdk\Customer\Customer(
    [
        'address' => [],
        'phone' => []
    ]
);

$transaction = $pagarMe->transaction()->creditCardTransaction(
    1000,
    $card,
    $customer,
    1,
    true,
    'www.asd.com.br',
    ['idProduto' => 13933139],
    []
);
```

Mas são enviado os dados do customer, mas com valores null e a API acaba verificando e barrrando, mesmo com antifraude.

*Talvez seja problema da API?*

Obrigado

**Comment by ricardotulio** [comment]
Fala @henriquekano, blz?

Conforme a doc da [API](https://docs.pagar.me/api/#criando-uma-transacao), esses campos são obrigatórios quando o *antifraude estiver habilitado*. 

Abraço!

**Comment by fernandoval** [comment]
Tem algo de estranho nessa sua afirmação.

Pois estou trabalhando na migração para a v3 do SDK de um projeto que tem a versão 1 do SDK instalada e funcionando. Com o antifraude está desabilitado.

Mas quando tento criar uma transação com a nova SDK, tomo erro:

> Unknown Error (0): Call to a member function getStreet() on null in /media/sf_scire/system/vendor/pagarme/pagarme-php/lib/Transaction/Request/TransactionCreate.php on line 51

Se acrescento os dados vazios, tomo outro erro:

> Unknown Error (0): "{\"errors\":[{\"parameter_name\":\"customer[address][zipcode]\",\"type\":\"invalid_parameter\",\"message\":\"CEP est\u00e1 faltando\"},{\"parameter_name\":\"customer[address][neighborhood]\",\"type\":\"invalid_parameter\",\"message\":\"bairro est\u00e1 faltando\"},{\"parameter_name\":\"customer[address][street]\",\"type\":\"invalid_parameter\",\"message\":\"rua est\u00e1 faltando\"},{\"parameter_name\":\"customer[address][street_number]\",\"type\":\"invalid_parameter\",\"message\":\"n\u00famero da rua est\u00e1 faltando\"},{\"parameter_name\":\"customer[phone][number]\",\"type\":\"invalid_parameter\",\"message\":\"n\u00famero de telefone est\u00e1 faltando\"},{\"parameter_name\":\"customer[phone][ddd]\",\"type\":\"invalid_parameter\",\"message\":\"DDD est\u00e1 faltando\"}],\"url\":\"\/transactions\",\"method\":\"post\"}" in /media/sf_scire/system/vendor/pagarme/pagarme-php/lib/Client.php on line 69

**Comment by devdrops** [comment]
Olá @fernandoval!

> Mas quando tento criar uma transação com a nova SDK, tomo erro:

Pode por favor passar um exemplo de como está fazendo a transação?

**Comment by fernandoval** [comment]
```
$address = new \PagarMe\Sdk\Customer\Address([]);

$phone = new \PagarMe\Sdk\Customer\Phone([]);

$customer = $pagarMe->customer()->create(
    'Joselito Sem Noção',
    'joselito@mailinator.com',
    '03071550308', // Gerado via gerador de CPF
    $address, // Criado acima com a classe de vocês
    $phone // Criado acima com a classe de vocês
);

$transaction = $pagarMe->transaction()->boletoTransaction(
    10000,
    $customer,  // Criado acima com a classe de vocês
    'http://requestb.in/u6zg6fu7'
);
```

**Comment by daniel2mind** [comment]
Pessoal, estou passando pelo mesmo problema do @fernandoval 

Ao tentar realizar a transação, mesmo com o Antifraude desabilitado, ele retorna o mesmo erro:

**in SubscriptionCreate.php: Call to a member function getStreet() on null**

Consigo buscar o plano pelo webservice e tudo mais... mas na hora de confirmar a assinatura, através do método createCardSubscription, retorna o erro acima.


Segue abaixo o código, onde estou tratando os dados:

`$apiKey = 'MINHA_API_KEY';
$pagarMe =  new PagarMe($apiKey);
$subscription = new \PagarMe\Sdk\Subscription\SubscriptionHandler($pagarMe->getClient());

        /*
         *  Dados para subscription
         * 
         */


        $plan = new \PagarMe\Sdk\Plan\PlanHandler($pagarMe->getClient());
        $plan = $plan->get("ID_DO_PLANO");

        $card = new \PagarMe\Sdk\Card\Card(array(
            'hash' => $request['pagarme']['card_hash']
        ));

        $address  = new \PagarMe\Sdk\Customer\Address([]);
        $phone    = new \PagarMe\Sdk\Customer\Phone([]);
        $customer = new \PagarMe\Sdk\Customer\Customer(array(
            'email' => $request['email'],
            $address,
            $phone
        ));
        

        $subscription->createCardSubscription(
            $plan,
            $card,
            $customer,
            url('')
        );`

**Comment by devdrops** [comment]
@fernandoval e @daniel2mind

Muito obrigado pelas informações. Vamos lá:

 - Sobre objetos `\PagarMe\Sdk\Customer\Address` e `\PagarMe\Sdk\Customer\Phone` vazios passados para `\PagarMe\Sdk\Customer\Customer`:

	Conforme explicado na [documentação da API](https://docs.pagar.me/api/#criando-uma-transacao), para criar uma transação são necessários os dados do endereço e contato do cliente. Se tais dados estiverem ausentes, a API devolverá `400 Bad Request` orientando o preenchimento dos campos, conforme o exemplo citado pelo @fernandoval [aqui](https://github.com/pagarme/pagarme-php/issues/138#issuecomment-293735069).

    Segue exemplo:

    ```php
    include __DIR__.'/vendor/autoload.php';

    $pagarMe = new \PagarMe\Sdk\PagarMe('my_api_key_goes_here');

    $card = $pagarMe->card()->create(
        '4242424242424242',
        'JOHN DOVE',
        '0722'
    );

    $address = new \PagarMe\Sdk\Customer\Address([
        'street' => 'Rua Cláudio Manoel da Costa',
        'streetNumber' => '492',
        'neighborhood' => 'Cristóvão Colombo',
        'zipcode' => '29106-430',
        'complementary' => '',
        'city' => 'Vila Velha',
        'state' => 'ES',
        'country' => 'Brasil'
    ]);

    $phone = new \PagarMe\Sdk\Customer\Phone([
        'ddd' => '27',
        'number' => '29937207'
    ]);

    $customer = $pagarMe->customer()->create(
        'John Dove',
        'john@site.com',
        '90879223022',
        $address,
        $phone,
        '17011990',
        'M'
    );

    $transaction = $pagarMe->transaction()->creditCardTransaction(
        1234,
        $card,
        $customer,
        1,
        true,
        'http://mystore.com/my-postback-route'
    );

    var_dump($transaction->getStatus()); // string(10) "processing"

    ```

- Sobre criação de assinatura:

	@daniel2mind não há a necessidade de instanciar diretamente um objeto de `\PagarMe\Sdk\Plan\PlanHandler`; basta usar os métodos da classe principal `\PagarMe\Sdk\PagarMe`, descritos em nossa [documentação](https://github.com/pagarme/pagarme-php/wiki/Assinaturas).

    Segue exemplo:

    ```php
    include __DIR__.'/vendor/autoload.php';

    $pagarMe = new \PagarMe\Sdk\PagarMe('my_api_key_goes_here');

    $card = $pagarMe->card()->create(
        '4242424242424242',
        'JOHN DOVE',
        '0722'
    );

    $address = new \PagarMe\Sdk\Customer\Address([
        'street' => 'Rua Cláudio Manoel da Costa',
        'streetNumber' => '492',
        'neighborhood' => 'Cristóvão Colombo',
        'zipcode' => '29106-430',
        'complementary' => '',
        'city' => 'Vila Velha',
        'state' => 'ES',
        'country' => 'Brasil'
    ]);

    $phone = new \PagarMe\Sdk\Customer\Phone([
        'ddd' => '27',
        'number' => '29937207'
    ]);

    $customer = $pagarMe->customer()->create(
        'John Dove',
        'john@site.com',
        '90879223022',
        $address,
        $phone,
        '17011990',
        'M'
    );

    $plan = $pagarMe->plan()->create(
        4990,
        30,
        'Meu Plano Especial',
        0,
        ['credit_card'],
        null,
        1
    );

    $subscription = $pagarMe->subscription()->createCardSubscription(
        $plan,
        $card,
        $customer,
        'http://mysite.com/my-route'
    );

    var_dump($subscription->getStatus()); // string(10) "paid"
    ```

É preciso destacar que a série de releases `V3` deste SDK fornece formas de uso diferentes das mesmas usadas nas versões mais antigas. Sugiro que leiam a [documentação atual](https://github.com/pagarme/pagarme-php/wiki) para seguirem com as implementações, e, em caso de dúvidas, não deixem de entrar em contato conosco :wink:

**Comment by fernandoval** [comment]
Prezado @devdrops você choveu no molhado. Não explicou coisa nenhuma.

A questão é que a afirmação do @ricardotulio não é coerente. Na versão 1.1 do SDK eu consigo criar transações sem fornecer número do documento, endereço e telefone do comprador porque minha conta está com o antifraude desligado.

A SDK 3 simplesmente ignora esse fato e não me permite criar transações sem fornecer os dados.

O que prova que isso não é uma limitação da API e sim do SDK.

Ou seja a SDK v3 é incompatível com a conta de quem não tem antifraude.

A solução então é estacionar na v1.1 do SDK e ignorar completamente qualquer nova versão?

**Comment by xduh** [comment]
Boa tarde @fernandoval @daniel2mind, na versão 3.1.8 é possível realizar transações sem informar os dados de endereço/telefone do customer.
Note que ainda é necessário passar um objeto `\PagarMe\Sdk\Customer\Customer` para realizar as transações, contudo caso não existam informações de endereço/telefone esses objetos não estarão presentes na requisição.

**Comment by daniel2mind** [comment]
Boa tarde pessoal...

@devdrops agora sim deu certo!  Realmente a documentação que estávamos utilizando, não se referia a versão da API que baixamos.

Creio que poderia ser criada uma última Tag estável do código, ou até mesmo disponibilizar ou informar sobre a versão nova da documentação. Pois no site da Pagar-me há muitas referências da documentação antiga, e isso nos confundiu!

No caso, perdemos algum tempo considerável apenas por utilizar a documentação incorreta.

Mas vamos ajustando para todos conseguirmos integrar, sem problemas!

Eu sigo à disposição, para ajuda ou informações.
Grande abraço.

**Comment by ansanelli** [comment]
@daniel2mind consegue dizer qual o codigo vc teve sucesso? estou com o mesmo problema, nem o suporte deles consegue me ajudar.

**Comment by muriloazevedo** [comment]
Boa tarde, 

Estou passando pelo mesmo problema. Preciso criar uma transação sem passar telefone e endereço, porém estou usando a última versão da SDK. O que descobri vendo a documentação:

o endpoint /transactions não tem como obrigatório os dados de endereço e telefone, como consta aqui:
https://docs.pagar.me/v2017-08-28/reference#criar-transacao

Diferente do endpoint do customer que exige endereço e telefone
https://docs.pagar.me/v2017-08-28/reference#criando-um-cliente

Diante disso, parece que não é possível criar a transação pela SDK, sem os dados do customer, correto?
