### ISSUE TITLE
Validação de POSTback

### ISSUE THREAD

**Issue by dcheloni** [pagarme/pagarme-php#142]
Na api v2 existia uma forma de validar as notificações recebidas utilizando: `PagarMe::validateRequestSignature(file_get_contents('php://input'), $_SERVER['HTTP_X_HUB_SIGNATURE'])`

Qual a forma de validar utilizando a api v3?
_Obs.: Não achei na documentação._

**Comment by xduh** [comment]
@dcheloni realmente, estava faltando na doc, acabei de adicionar em https://github.com/pagarme/pagarme-php/wiki/POSTback#validando-um-postback, a sintaxe é:
```php
$postback = $pagarMe->postback()->validateRequest(
    'data=false&random=postback&any=content',
    'sha1=0c533b2efaccae059e741a50babd3e3dd51d466b'
);
```
