### ISSUE TITLE
Criação de conta bancária desconforme com API

### ISSUE THREAD

**Issue by xduh** [pagarme/pagarme-php#144]
Ao criar contas bancárias não existe a possibilidade de informar o tipo de conta (conta_corrente, conta_poupanca, conta_corrente_conjunta, conta_poupanca_conjunta) conforme em https://docs.pagar.me/api/#criando-uma-conta-bancaria.

**Comment by ricardotulio** [comment]
@xduh isso é [V3](https://github.com/pagarme/pagarme-php/tree/V3)?

**Comment by xduh** [comment]
Exato
