### ISSUE TITLE
Problema ao instalar a biblioteca no Laravel 5.4

### ISSUE THREAD

**Issue by jonasantonelli** [pagarme/pagarme-php#148]
## Contexto

Ao tentar rodar o `composer require pagarme/pagarme-php` foi notificado que a versão necessário do Guzzle é conflitante com a versão necessário do Guzzle para o Laravel.

## Possível correção

Atualizar a versão necessário do Guzzle na biblioteca do Pagarme para uma versão compatível com a do Laravel 5.4.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/5802946/23971984/de00caba-09ae-11e7-9d0d-d0a9577f92b2.png)

![image](https://cloud.githubusercontent.com/assets/5802946/23971996/e90e6a16-09ae-11e7-87a7-4fb8ae21ba4c.png)

**Comment by devdrops** [comment]
Olá @jonasantonelli, @filipegar, @DiSiqueira e @flicsl!

Como explicado em #152: por razões de suporte, infelizmente precisamos manter o suporte para PHP 5.4 na série de releases `v3.*`. Estamos com projetos ativos no roadmap para plataformas exclusivas com dependência dessa versão e que estão limitadas nessa versão do PHP, portanto a alteração do `guzzlehttp/guzzle` não pode ser realizada neste momento.

Como ainda não temos definido no roadmap o momento exato para depreciar esse suporte, peço que por favor mantenham esta issue em aberto pois assim podemos manter isso no radar para execução.

**Comment by filipegar** [comment]
@devdrops considerem usar algo como o php-http/httplug na próxima serie.

**Comment by socramjunio2** [comment]
@jonasantonelli Crie uma pasta chamada packets, inclua lá o seu pagarme-php através do git, após isso inclua no seu composer:

`
"autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
	    "Packets\\": "packets/"
        }
    },
`

Assim você vai ter o pacote apenas do git, podendo alterar e adaptar você mesmo, já que o Pagar.me ainda não pode.

@pedrofranceschi 
Faça um novo pacote, descontinue este, assim você nos ajuda e sempre ter as coisas atualizadas e seguras.

**Comment by flyingluscas** [comment]
@jonasantonelli O problema não é necessariamente com o Laravel 5.4, isso ocorre porque no seu `composer.json` você está forçando o Guzzle ^6.2, sem isso você consegue instalar a SDK sem problema nenhum, também fiz testes com outras versões do Laravel 5.* e está tudo funcionando :)

**Comment by filipegar** [comment]
@flyingluscas tá no upgrade guide que o [Laravel 5.4](https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0) precisa do Guzzle ^6.0. Regredir a versão no `composer.json` até resolve para instalar o pagarme, mas outros recursos do laravel (como uso das apis do mailgun ou do socialite) deixam de funcionar.

**Comment by flyingluscas** [comment]
@filipegar Sim, minha sugestão foi mais para tentar resolver este problema em específico, mas ainda estamos analisando esta caso para ver qual a melhor solução.

**Comment by xduh** [comment]
corrigido em #195
