### ISSUE TITLE
Quando a assinatura está em teste, ao recuperá-la, como não tem transação, dá erro

### ISSUE THREAD

**Issue by tiagoa** [pagarme/pagarme-php#151]
## Contexto

Quando a assinatura está em teste, ao recuperá-la, como não tem transação, o SubscriptionBuilder tenta setar a current_transaction com buildTransaction fornecendo um valor vazio.

## Possível correção

O que eu fiz foi verificar se a current_transaction do Subscription não é vazia antes de tentar executar o buildTransaction:

`$subscriptionData->current_transaction = $subscriptionData->current_transaction ? $this->buildTransaction($subscriptionData->current_transaction) : [];
`

**Comment by socramjunio2** [comment]
Opa. aconteceu a mesma coisa comigo, então alterei o arquivo, aguardo a solução!

A minha alteração foi a seguinte:
![image](https://cloud.githubusercontent.com/assets/21258161/25558590/398d3200-2d00-11e7-993e-bed87a588ede.png)
para:
![image](https://cloud.githubusercontent.com/assets/21258161/25558592/440aa97e-2d00-11e7-84da-35ac0b09c0a1.png)
Seguindo assim a mesma verificação do Card logo acima, espero ter ajudado!

**Comment by socramjunio2** [comment]
PS: Preciso do update para não ter que deixar o arquivo mexido!

**Comment by socramjunio2** [comment]
Alguma posição ??

**Comment by xduh** [comment]
Resolvido em #188
