### ISSUE TITLE
SDK V3 - Dúvidas

### ISSUE THREAD

**Issue by lucascolette** [pagarme/pagarme-php#163]
Essa V3 do SDK já está disponível para rodar em produção? É que não vi na Wiki alguma menção sobre o card_hash e também na criação de um cartão o CVV não é informado.

**Comment by devdrops** [comment]
Oi @lucascolette! Vamos lá:

> Essa V3 do SDK já está disponível para rodar em produção?

Sim. É a base das releases, já disponíveis no [Packagist](https://packagist.org/packages/pagarme/pagarme-php).

> É que não vi na Wiki alguma menção sobre o card_hash e também na criação de um cartão o CVV não é informado.

Sobre `card_hash`: pode por favor detalhar quais as suas dúvidas?
E sobre CVV: para criar um objeto `\PagarMe\Sdk\Card\Card`, esse valor não é necessário, conforme declarado na [documentação deste SDK](https://github.com/pagarme/pagarme-php/wiki/Cart%C3%B5es#criando-um-novo-cart%C3%A3o-para-uso-futuro) e na [documentação da nossa API](https://docs.pagar.me/api/#criando-um-cartao).

**Comment by lucascolette** [comment]
@devdrops é que na [documentação](https://github.com/pagarme/pagarme-php/wiki/Cart%C3%B5es#criando-um-novo-cart%C3%A3o-para-uso-futuro) do Card não consta o objeto card_hash, por isso fiquei na dúvida se ele não é mais usado.

**Comment by lucascolette** [comment]
@devdrops acredito que tenha me confundido. Agora a transação pode ser criada diretamente com o objeto Card e não mais com o card_hash. Seria isso?

**Comment by devdrops** [comment]
> @devdrops acredito que me confundi. Agora a transação pode ser criada diretamente com o objeto Card e não mais com o card_hash. Seria isso?

Exato :wink:

**Comment by wagnerfr** [comment]
Pessoal, 
é a primeira vez que estou tentando usar o pagar.me e não sei se eu sou muito burro ou esta difícil de entender a documentação. Estou tomando um pau aqui. Já tentei utilizar o Checkout mas o ideal é utilizar o SDK de PHP.

Não consegui passar do início:
`<?php

    require 'lib/PagarMe.php';

    $ak_test = 'Minha ak_test'
    $pagarMe = new \PagarMe\Sdk\PagarMe($ak_test);`

Esta retornando o erro:
`Fatal error: Class 'PagarMe\Sdk\Client' not found in /Applications/XAMPP/xamppfiles/htdocs/pagarme-php/lib/PagarMe.php on line 137`

Obrigado.

**Comment by leonampd** [comment]
Oi @wagnerfr tudo bem?

Como vc fez a instalação do nosso SDK? Aparentemente o problema é que algumas outras classes, que são necessárias não estão sendo carregadas. Sugiro que você faça a instalação através do [Composer](http://getcomposer.org) já que ela está disponível no [Packgist](https://packagist.org/packages/pagarme/pagarme-php). Dessa forma basta definir a SDK como dependência do seu projeto.

A nossa SDK segue a  [PSR-4](http://www.php-fig.org/psr/psr-4/) então, você pode usar o Autoload que o composer fornece. Dessa forma, o trabalho de realizar o require das classes será feito pelo Composer e, provavelmente você não terá mais esse problema.

Seu arquivo deve ficar assim, basicamente:

```
<?php
    require 'vendor/autoload.php';

    $apiKey = 'Minha ak_test'
    $pagarMe = new \PagarMe\Sdk\PagarMe($apiKey);
```

Se tiver alguma dúvida em como utilzar o composer dê uma olhada na documentação, é bem simples. A documentação da nossa SDK de PHP vc encontra [aqui](https://docs.pagar.me/).
