### ISSUE TITLE
Invalid resource type: boolean in guzzleHttp

### ISSUE THREAD

**Issue by fernandoval** [pagarme/pagarme-php#164]
Estou trabalhando na migração da v1.1 para a v3 desse SDK e estou tomando erro quando tento criar transações. A versão 1.1 funciona perfeitamente.

> Unknown Error (0): Invalid resource type: boolean in /media/sf_scire/system/vendor/guzzlehttp/streams/src/Stream.php on line 85

Meu código:

```
$address = new \PagarMe\Sdk\Customer\Address([
    'street' => $customer->address,
    'street_number' => $customer->addrNumber,
    'complementary' => $customer->complement,
    'neighborhood'  => $customer->neighborhood,
    'city' => $customer->city,
    'state' => $customer->state,
    'zipcode' => $customer->zip,
]);

$phone = new \PagarMe\Sdk\Customer\Phone([
    'ddd' => $customer->ddd,
    'number' => $customer->phone,
]);

$customer = $pagarMe->customer()->create(
    $customer->name,
    $customer->email,
    $customer->documentNumber,
    $address,
    $phone
);

$transaction = $pagarMe->transaction()->boletoTransaction(
    $orderValue,
    $customer,
    postbackUrl()
);
```

**Comment by devdrops** [comment]
Oi @fernandoval!

Cara, poderia por favor passar um exemplo do teu código mas com dados similares ao que está usando? Pode ser dummy data mesmo, mas que seja do mesmo tipo (string, intgere, etc) que o seu código original.

**Comment by fernandoval** [comment]
Tá de brincadeira, né? Mas vai lá:

```
$address = new \PagarMe\Sdk\Customer\Address([
    'street' => 'Rua A',
    'street_number' => '1',
    'complementary' => 'Apto 2',
    'neighborhood'  => 'Sbroubles',
    'city' => 'Rio de Janeiro',
    'state' => 'RJ',
    'zipcode' => '20000000',
]);

$phone = new \PagarMe\Sdk\Customer\Phone([
    'ddd' => '21',
    'number' => '22334455',
]);

$customer = $pagarMe->customer()->create(
    'Joselito Sem Noção',
    'joselito@mailinator.com',
    '03071550308', // Gerado via gerador de CPF
    $address, // Criado acima com a classe de vocês
    $phone // Criado acima com a classe de vocês
);

$transaction = $pagarMe->transaction()->boletoTransaction(
    10000,
    $customer,  // Criado acima com a classe de vocês
    'http://requestb.in/u6zg6fu7'
);
```

**Comment by piiih** [comment]
@fernandoval desculpe a demora na resposta. Mas você ainda está com esse problema?

**Comment by fernandoval** [comment]
@piiih não sei. Para descobrir será preciso que eu retome a migração para a v3 do SDK.

O erro era porque a v3 do SDK não funcionava com o Guzzle 6 que era indispensável ao meu projeto pelo fato de ser dependência do SDK da AWS.

Infelizmente estou com outras tarefas mais importantes na fila e não dá para fazer esse teste.

**Comment by viniciusbiz** [comment]
@fernandoval também estava com o mesmo problema. @piiih como anda esta verificação?

**Comment by leonampd** [comment]
Olá pessoal, tudo bem?

Estou fechando essa issue dado que há agora uma nova versão estável do [SDK](https://github.com/pagarme/pagarme-php). Fiquem à vontade para abrir novamente caso julguem necessário.

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
