### ISSUE TITLE
Impossibilidade do envio do parâmetro soft_descriptor

### ISSUE THREAD

**Issue by vgsmith** [pagarme/pagarme-php#166]
## Contexto

Ao criar uma transação, não consigo enviar o parâmetro **soft_descriptor** disponível na API. Segue exemplo das tentativas:

```
['softDescriptor' => TESTE]
//OU
['soft_descriptor' => TESTE]

$extraAttributes = ['soft_descritor'     => $soft_descriptor]
```

## Ambiente

* SDK Pagar.me 3.1.8
* Servidor Linux
* PHP 5.4

## Passos para reproduzir

1. Definir o valor do soft_descriptor
2. Criar a transação, enviando o parâmetro acima em **$extraAttributes**

## Resultado esperado

No JSON de retorno da API, o esperado era:
`"soft_descriptor":"TESTE",`

## Resultado atual

Segue o JSON retornado:
`"soft_descriptor":null,`

**Comment by devdrops** [comment]
Oi @vgsmith! Acredita que o que temos neste PR https://github.com/pagarme/pagarme-php/pull/153 se relaciona com esta issue?
