### ISSUE TITLE
Criar cartão através da hash

### ISSUE THREAD

**Issue by DfKimera** [pagarme/pagarme-php#168]
Atualmente, via SDK, não é possível criar um `Card` através do `card_hash` gerado via Pagarme.js, [apenas com os dados completos do cartão](https://github.com/pagarme/pagarme-php/wiki/Cart%C3%B5es). Gostaria de realizar essa operação para evitar trafegar dados de cartão "abertos" via rede.

A criação via hash é possível usando a API REST, passando o parâmetro `card_hash` no lugar dos dados do cartão, mas a funcionalidade não é exposta na SDK PHP.

Sugiro a criação de um método `createFromHash(string $card_hash)` que permita essa operação.

Posso abrir um PR com esse objetivo, se for interessante.

Obrigado!

**Comment by xduh** [comment]
Boa noite @DfKimera, na documentação não está descrito, mas é possível utilizar um `card_hash` gerado pelo pagarme.js, para realizar uma transação no SDK PHP
```
$card = new \PagarMe\Sdk\Card(['hash' => $seuHash]);
```
Basta então passar esse objeto para o método `creditCardTransaction`.

**Comment by DfKimera** [comment]
@xduh Mas esse procedimento não gera um `cardId`, gera? O objetivo é guardar o `cardId` para realizar transações futuras.

**Comment by xduh** [comment]
Saquei, de fato hoje não é possível criar um cartão através do card_hash sem transacionar no SDK de PHP; Isso realmente precisaria ser implementado, você consegue tocar esse cara?

**Comment by DfKimera** [comment]
@xduh Fiz um pull request com o novo método. Abs!

**Comment by xduh** [comment]
Corrido em #171 
Tks @DfKimera
