### ISSUE TITLE
[ISSUE] Update Guzzle Library

### ISSUE THREAD

**Issue by lucianocn** [pagarme/pagarme-php#170]
This library is using an old Guzzle version, having problems together with other libraries (like `facebook/graph-sdk (beta)` / `intercom-php`).

In Use: 5.3
Latest: 6.2.3

`Your requirements could not be resolved to an installable set of packages.`

Fix: Please update to 6.x.

**Guzzle Upgrade Guide**
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by devdrops** [comment]
Olá @lucianocn!

Muito obrigado pela issue. O tópico desta issue já se encontra representado em outra issue (#148), e por essa razão fecharemos esta issue.
