### ISSUE TITLE
class TransactionCreate erro Array => Object

### ISSUE THREAD

**Issue by cavalomorreu** [pagarme/pagarme-php#173]
class TransactionCreate lines 47 .... 55

array $address to OBJECT
array $phone to OBJECT
![captura de tela 2017-04-29 as 02 02 51](https://cloud.githubusercontent.com/assets/5822617/25553084/efef5684-2c80-11e7-8943-031b990738a3.png)
![captura de tela 2017-04-29 as 02 03 00](https://cloud.githubusercontent.com/assets/5822617/25553085/eff03fcc-2c80-11e7-97b5-adf4dfa9fc46.png)
![captura de tela 2017-04-29 as 02 03 24](https://cloud.githubusercontent.com/assets/5822617/25553086/eff05caa-2c80-11e7-86a1-6a8ffac73125.png)

**Comment by devdrops** [comment]
Favor informar:

* Versão do SDK Pagar.me
* Versão do PHP
* Qualquer outra característica a ser considerada

**Comment by cavalomorreu** [comment]
SDK V3
PHP 5.5
Laravel 5.2

Outro problema: não esta notificando a minha url de retorno, não sei mais o que fazer.

![captura de tela 2017-04-29 as 21 55 41](https://cloud.githubusercontent.com/assets/5822617/25560310/c19b28b6-2d26-11e7-9dcd-f2d8c02023e6.png)
![captura de tela 2017-04-29 as 21 55 53](https://cloud.githubusercontent.com/assets/5822617/25560311/c19b8d9c-2d26-11e7-896e-cac93c91e8f8.png)
![captura de tela 2017-04-29 as 21 56 04](https://cloud.githubusercontent.com/assets/5822617/25560312/c19bf7f0-2d26-11e7-9035-a7954c6e1cf7.png)

**Comment by cavalomorreu** [comment]
Obs: estou desenvolvendo em dois ambientes um localhost e um online, ambos com a mesma configuração e realizo os testes no online, mesmo assim o sistema da pagar.me não esta acessando minha url fornecida para fazer a mudança de status.

**Comment by cavalomorreu** [comment]
Achei o erro do "postbackUrl", a SDK V3 não esta enviando a URL postbackUrl para o sistema da pagar.me segue o erro.

Arquivo: TransactionHandler.php na linha 87 tem uma key do array que foi passada errado:

Troque o key "postBackUrl" para "postbackUrl"

Dica: eu tenho tive e ainda tenho diversos problemas com ambientes onde o sensitive case esta desativado e o desenvolvimento funciona e depois ao migrar para um ambiente com o sensitive case ativo o projeto não rodar nada bem, verifiquem as chaves.

Obrigado!

![captura de tela 2017-04-29 as 22 20 50](https://cloud.githubusercontent.com/assets/5822617/25560415/51b4d354-2d2a-11e7-91c1-4850fcddfb75.png)
![captura de tela 2017-04-29 as 22 22 15](https://cloud.githubusercontent.com/assets/5822617/25560414/51b3600a-2d2a-11e7-9ab2-4271e9b64662.png)

**Comment by cavalomorreu** [comment]
O método buildTransaction não retorna a url e código do boleto, eu vejo que no $response do método boletoTransaction tem  a url e código do boleto, porém quando ele passa para o método buildTransaction ele não retorna mais esses dados, tem alguma forma correta de pegar a url e código do boleto?

**Comment by cavalomorreu** [comment]
Para conseguir os dados do boleto eu tive que adicionar dois metodos na class AbstractTransaction, segue:

public function  getBoletoBarcode(){
        return $this->boletoBarcode;
    }

    public function  getBoletoUrl(){
        return $this->boletoUrl;
    }

**Comment by cavalomorreu** [comment]
Agora deu certo! :)

**Comment by cavalomorreu** [comment]
SDK V3
PHP 5.5
Laravel 5.2

Call to undefined method PagarMe\Sdk\Postback\PostbackHandler::validateRequest()
Código: $postback = $pagarMe->postback()->validateRequest

**Comment by piiih** [comment]
@cavalomorreu desculpe a demora da resposta. Mas você ainda está tendo problemas?
