### ISSUE TITLE
Sdk\Customer não retorna o parâmetro de endereço na sua Linha de Comentário do Phone do Address 

### ISSUE THREAD

**Issue by socramjunio2** [pagarme/pagarme-php#174]
Sdk\Customer não retorna o parâmetro de endereço na sua Linha de Comentário do Phone do Address..

Não influencia em nenhum bug, mas isso é uma mão na Roda para IDE identificar os Objetos retornados, 

Screenshot da minha alteração:
![image](https://cloud.githubusercontent.com/assets/21258161/25558892/65e3460e-2d06-11e7-8e96-81c1c7fca743.png)

**Comment by devdrops** [comment]
Favor seguir a formatação original para issues, conforme [modelo](https://github.com/pagarme/pagarme-php/blob/V3/.github/ISSUE_TEMPLATE.md).

**Comment by devdrops** [comment]
Oi @socramjunio2!

Pela necessidade de seguir um padrão para report de issues, solicitamos que seja seguido o formato que propomos, conforme [modelo](https://github.com/pagarme/pagarme-php/blob/V3/.github/ISSUE_TEMPLATE.md).

Como o padrão não foi seguido, vamos fechar esta issue. Caso tenha necessidade de seguir com o assunto, peço que edite o formato e reabra esta mesma issue. Ou caso preferir, pode abrir um pull requetst com as alterações necessárias.
