### ISSUE TITLE
API Retorna 504 (Gateway Timeout) quando os atributos de phone são inteiros na criação de uma assinatura

### ISSUE THREAD

**Issue by gstpreira** [pagarme/pagarme-php#179]
## Contexto

Toda vez  que qualquer um dos atributos do objeto phone(ddd, number) são inteiros acontece um erro na API, o erro não tem nada a ver com o SDK mas sim quando com o endpoint da API, e a documentação não é falado se o campo deve ser string ou inteiro.

O erro mencionado foi somente testado no endpoint de criação de assinatura, os outros não foram testados.

https://docs.pagar.me/api/?shell#criando-assinaturas

## Ambiente

Foi testado usando a V3 do SDK PHP, request por Postman e em cURL

## Passos para reproduzir

`curl -X POST https://api.pagar.me/1/subscriptions \
-H 'Content-Type: application/json' \
-d '{"plan_id": 123,"payment_method": "boleto","metadata": {"idProduto": 123},"customer": {"name": "João Teste","email": "joaotest@email.com","address": {"street": "Rua teste","street_number": 123,"neighborhood": "Ali Teste","zipcode": "15900000"},"phone": {"ddd": 16,"number": "123456789"},"born_at": null,"gender": null    },    "postback_url": "http://requestb.in/zyn5obzy", "api_key": "API_KEY"}'`

## Resultado esperado

Teria que ser criado a assinatura, ou mesmo estar na documentação o tipo que o parâmetro é esperado.

## Resultado atual

Há um retorno de 504 Gateway Timeout sem mensagem alguma
 
@xduh @devdrops

**Comment by devdrops** [comment]
Oi @gstpreira, tudo certo?

Muito obrigado pela issue! Já reportamos o cenário aqui e estamos avaliando as correções para isso. Ainda não temos uma previsão exata para publicar uma correção para isso, então peço que por favor, caso tenha quaisquer dúvidas, entre em contato conosco nesta mesma issue.

**Comment by gstpreira** [comment]
Muito obrigado pelo retorno, @devdrops :D

**Comment by socramjunio2** [comment]
10 dias e até agora nada ?

**Comment by xduh** [comment]
@socramjunio2 você tem algum problema relacionado a esta issue? pode detalhar?
