### ISSUE TITLE
Atualização do Guzzle..

### ISSUE THREAD

**Issue by dann95** [pagarme/pagarme-php#185]
## Contexto

Passar a utilizar guzzle ^6 , pois a versão 5.3 gera conflito com algumas outras libs que já usam a versão 6.2... https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by ricardotulio** [comment]
Olá @dann95, tudo bem?

Para facilitar a integração com plataformas como Magento, OSCommerce, Prestashop e outras plataformas escritas em PHP, elas utilizam a SDK, e boa parte dessas plataformas dão suporte para o PHP versão 5.4+. Se atualizarmos hoje para o Guzzle 6, quebramos a integração com algumas plataformas. 

Ainda estamos procurando uma forma de como permitir o uso do Guzzle 5 e 6, pois não podemos deixar de dar o suporte ao PHP 5.4 para não parar alguns clientes e restringir o uso das integrações pelas plataformas.

**Comment by dann95** [comment]
Simples, fazemos uma interface para o "Http Client", versões de magento e etc podem usar uma implementação com curl puro, em alguma classe implementando a interface PagaMeHttpClient, é possível fazer módulos para Laravel/Lumen que são muito usados, se quiserem contribuições, posso colaborar. (adoro Laravel).

**Comment by dann95** [comment]
```php
<?php

interface PagarMeHttpClient
{
public __construct(GuzzleClient $client, $apiKey, $timeout = null);
public function setDefaultTimeout($timeout);
public getDefaultTimeout();
public function send(RequestInterface $apiRequest)
public function getApiKey()
}

```
Hoje ela se parece a algo como descrito acima, mas seria interessante uma interface como:
```php
<?php


interface PagarMeHttpClient
{
    public function __construct(array $headers = [], $timeout = 0);

    public function setHeaders(array $headers = []);

    public function setTimeout($timeout = 0);
    
    public function setRequest(RequestInterface $request);

    public function send();

    public function decodeResponse();
}
```
Inclusive por questão de responsabilidade se pode separar o "decodeResponse" mas isso visando se sei lá amanhã da a doida em vocês e a api responde com XML hahahaa (brinks), a sdk de vocês é legal e bem pensada, mas não vejo muitas interfaces, o que complica multiplas implementações.. bom se quiser ajuda só da um grito.

att Daniel

**Comment by socramjunio2** [comment]
@dann95 @ricardotulio essa questão está bem complicada, a sugestão é boa de usar a interface e poderia ser aplicada logo, e parar de ficar pensando em coisas complicadas, a interface resolveria mesmo o problema. Outra coisa que pode ajudar é detectar a versão do Guzzle, e assim nessa interface injetar os serviços corretos.. Aguardo emergência nesse assunto!

**Comment by dann95** [comment]
emergência..

**Comment by xduh** [comment]
@socramjunio2 @dann95 fiquem a vontade para abrir PR's relacionados a isso, que atendam as necessidades explanadas.

**Comment by dann95** [comment]
Seria possível então abrir um branch chamado "php7" , para fazer a implementação a interface com Guzzle ^6 ? 

att Daniel

**Comment by xduh** [comment]
@dann95 o ideal é uma solução que atenda 5.4+

**Comment by dann95** [comment]
Então se trata de remover o guzzle, e usar curl puro. ok, estarei vendo de fazer uma pr mais tarde.

**Comment by KennedyTedesco** [comment]
Realmente, não consigo usar essa versão em nenhum dos meus projetos, nem mesmo no meu maior projeto em que usamos o Pagar.me. A minha stack é PHP 7.1 e a maioria das minhas dependências utilizam Guzzle 6.

Acho que uma boa alternativa pra gente seria utilizar:

http://httplug.io/

E aqui um Usage Guide:

http://docs.php-http.org/en/latest/httplug/library-developers.html

Infelizmente não disponho de tempo pra tal implementação, senão faria com todo amor. ❤️ 

Espero que consigamos avançar aqui e que alguém envie uma solução. =)

**Comment by dann95** [comment]
@KennedyTedesco com a pressa deles, meu chefe segue sem usar Pagarme.. mas é vida que segue =p

**Comment by KennedyTedesco** [comment]
@dann95 Poxa, que pena. É realmente chato esse tipo de "embargo". Torçamos pra uma resolução! =)

**Comment by dann95** [comment]
@KennedyTedesco pagar.me não tem as melhores taxas, e realmente não se importam com a sdk em php rsrsrsrs, meu chefe queria o pagar.me como métod secundário, torcer pra uma resolução chega a ser bizarro, se o problema é compatibilidade, simplesmente usem curl puro..

**Comment by xduh** [comment]
Corrigido em #195, disponível na versão 3.3.1
