### ISSUE TITLE
Associar um customer a um cartão ou um cartão a um customer

### ISSUE THREAD

**Issue by VictorMessina** [pagarme/pagarme-php#186]
## Contexto

Quando o cliente foi criar uma transação via cartão o custoemr da transação não foi associado ao cartão utilizado e quando fui verificar o código não existia um SET para realizar essa ação.

Na PHP V2 essa atribuição acontecia automaticamente.

## Ambiente

SDK PHP V3

## Passos para reproduzir

1º Criar um Card em nossa base de dados passa um customer no construtor do cartão.

2º Verificar se o customer foi atribuido ao cartão criado (GET no \cards\id_do_cartão)

## Resultado esperado

Criar um vinculo entre o cartão e o customer no momento da criação da transação e criar esse mesmo vinculo entre customer e cartão quando o cartão for utilizado na transação.

## Resultado atual

O SDK simplesmente ignora o parâmetro customer passado.

## Possível correção

Criação de um SET para o  parâmetro customer na Classe Card

**Comment by leonampd** [comment]
Dado que há uma nova versão do [SDK](https://github.com/pagarme/pagarme-php) estou fechando essa issue, ok?
