### ISSUE TITLE
[NFR] Não permite criar transferência entre recebedores

### ISSUE THREAD

**Issue by williamokano** [pagarme/pagarme-php#189]
## Contexto
Ao criar uma transação é possível que seja solicitado um TED ou então que seja feita uma transação entre recebedores utilizando os parâmetros `source_id` e `target_id` (parâmetros não documentados), porém via SDK V3 isso não é possível.

## Ambiente

* SDK Pagar.me V3
* Servidor Linux Mint
* PHP 5.6

## Passos para reproduzir
Não há como reproduzir, o comportamento espera que no método `create` do TransferHandler receba um objeto `Recipient` e o outro seja `BankAccount`.

## Resultado esperado
Espera-se que seja possível criar uma transferência entre 2 recebedores e não apenas para contas bancárias.

## Resultado atual
Não permite que seja transferido valores entre diferentes recebedores.

## Possível correção
Implementar o método que envie os parâmetros descritos na contextualização.

**Comment by redhmam** [comment]
Isto é possível?

**Comment by williamokano** [comment]
Sim, mas não está documentado; realmente não sei se deveria de conhecimento
público anyway

Em 18 de out de 2017 2:09 PM, "Redhmam" <notifications@github.com> escreveu:

**Comment by williamokano** [comment]
Apesar de existir alguns contratempos com essa operação, por exemplo, se você quer transferir entre *A* e *B* e nem *A* nem *B* são contas _default_, tu vai ter que fazer 2 operações

*A* -> _default_
_default_ -> *B*

Onde, obviamente, umas das duas pode falhar e não tem como fazer isso ser transacionado, então tem que ter um workflow bem definido pra fault tolerance e seguir de onde parou.

**Comment by redhmam** [comment]
Na regra de negócio que estou implementando, só sei quem é o recebedor depois da transação. Precisava fazer a transferência da conta default para uma conta x (outro titular). Isso seria possível então?

Obs: Sei que posso trabalhar no modo de captura, porém este modo não funciona com boleto.

**Comment by williamokano** [comment]
Você não está passando split de pagamento? Se não estiver passando ele já vai cair por padrão na conta default.

No caso seria melhor ver essas operações com o suporte deles, ou então algum dev lá de dentro, tipo o xduh , MarcoWorms, vgsmith, devdrops, ThamaraHessel 

PS.: não marque as arrobas deles pra não notificar eles.

**Comment by devdrops** [comment]
@williamokano pode marcar a gente sem problemas, é importante pra gente saber quais as necessidades para entender melhor como podemos ajudar :wink:

**Comment by redhmam** [comment]
Obrigado @williamokano !

**Comment by redhmam** [comment]
@devdrops Opa Davi! Minha dúvida é se consigo transferir da conta default para outra conta de outro titular pois em contato com o comercial me disseram que não era possível.

Na regra de negócio que estou implementando, sabemos quem vai receber somente depois que a transação acontece, logo não consigo implementar com split rule, e o modelo de captura não é o ideal para mim, pois trabalhamos também com boleto bancário.

Você tem algum informação a respeito?

**Comment by murilohns** [comment]
Fala pessoal, boa tarde.

Não é possível fazer transferência entre recebedores, se trata de uma trava na API do Pagar.me.

Estou fechando essa _issue_, mas sintam-se a vontade para reabri-la caso necessitem.

**Comment by williamokano** [comment]
@murilohns isso é recente? Fiz uma integração recentemente para a ricardo eletro e é possível sim, inclusive utilizando a API; o que não achei foi como fazer isso via SDK.

**Comment by murilohns** [comment]
@williamokano Sim, essa foi uma decisão tomada recentemente por motivos estratégicos da empresa.

**Comment by williamokano** [comment]
Entendi. Interessante. Bom, então é closed mesmo hehehe
