### ISSUE TITLE
[NFR] Não é possível definir o charge_remainder nas regras de split SDK V3

### ISSUE THREAD

**Issue by williamokano** [pagarme/pagarme-php#190]
## Contexto
Algumas vezes as taxas são cobradas de um recebedor mesmo que ele esteja definido como não responsável pela taxa de transação; aparentemente quando há quebra de centavos o valor é jogado no primeiro recebedor do split.

Para evitar que isso aconteça é possível enviar o parâmetro `charge_remainder` (não documentado) para explicitar qual regra de split será responsável pela quebra de centavos da taxa, porém não é possível definir essa opção via SDK.

## Ambiente

* SDK Pagar.me V3 (dev-master)
* Servidor Linux Mint 18
* PHP 5.6

## Passos para reproduzir
Não há como reproduzir visto que é uma new feature request.

## Resultado esperado
Que seja possível definir qual regra de split será realmente responsável pela quebra da diferença da taxa.

## Resultado atual
Não existe a opção de definir qual regra de split será responsável pela quebra da diferença da taxa.

## Possível correção
Adicionar a opção na `monetaryRule` e na `percentageRule` como último parâmetro, assim não quebra a compatibilidade com as versões anteriores.

## Screenshots

**Comment by xduh** [comment]
Resolvido em #192 
Tks @williamokano
