### ISSUE TITLE
[NFR] Definir regra de split no estorno

### ISSUE THREAD

**Issue by williamokano** [pagarme/pagarme-php#191]
## Contexto
No contexto de um marketplace, geralmente cada recebedor possuirá uma, ou mais, contas vínculadas à sua loja. Em uma venda com múltiplos produtos de múltiplas lojas, é comum que o pagamento seja dividido entre vários recebedores via `split_rules`. Quando existe um estorno, seja por cancelamento de um único item do pedido, um parceiro não entregou o item a transportadora, ou qualquer outro motivo que venha a ocorrer o reembolso de apenas um item pontual, o estorno deveria ocorrer apenas no recebedor (ou na regra de split) definida, não penalizando as outras lojas que participaram da venda, visto que a o estorno dilui o valor estornado proporcionalmente entre todos os recebedores (e split rules).

## Ambiente
* SDK Pagar.me V3
* Servidor Linux Mint 18
* PHP 5.6

## Passos para reproduzir
- Criar uma transação com várias split rules, cada split rule simbolizando uma loja de um marketplace;
- Autorizar e capturar a transação;
- Solicitar estorno do valor de apenas 1 item (ou de uma split rule inteira).
- O valor foi removido proporcionalmente de todos os splits porque não existe como definir, via SDK, qual split e qual recebedor quero que seja removido este valor.

**Estorno com split rule é uma operação com parâmetros não documentados na API**

## Resultado esperado
Espera-se que o valor seja removido apenas do "split/loja" que realmente teve sua parte "cancelada".

## Resultado atual
Todos tem valores removidos pois não é possível passar as regras de split.

## Possível correção
Enviar junto com o refund um array de regras de split para que seja estorno de acordo com essas regras, caso enviadas.

## Screenshots

**Comment by topogigiovanni** [comment]
Hoje é possível fazer "no braço" como demonstrado no exemplo em cUrl deste [link](https://docs.pagar.me/reference#estorno-parcial-com-split). Mas seria realmente muito útil isso estar acoplado a SDK 👍

**Comment by williamokano** [comment]
Opa @topogigiovanni bom lembrar que quando eu escrevi essa issue, na época não havia documentação de como realizar o refund com split. Agora que me atentei com um negrito gigante falando que não é documentada kkkkk

**Comment by topogigiovanni** [comment]
hehehhehhe
@williamokano apenas confirmando, hoje o único jeito de fazer a ação de refund com split utilizando a V3 seria via cUrls mesmo?

**Comment by williamokano** [comment]
Acredito que sim, hoje faço via curl mesmo

**Comment by leonampd** [comment]
Oi @williamokano tudo bem?

Dado que temos uma nova versão do [SDK](https://github.com/pagarme/pagarme-php) estou fechando essa issue, tudo bem? Se julgar necessário fique a vontade para abrir essa issue.
