### ISSUE TITLE
Pagamento com cartão não aprovado (API LIVE) retornam Internal Server Error 500

### ISSUE THREAD

**Issue by dilersik** [pagarme/pagarme-php#193]
## Contexto
Os cartões válidos, mas que não deveriam aprovar a transação, seja por CVV incorreto ou qualquer outro motivo, ao invés de retornar “acquirer refused” retornam:
Failed to decode json from response. Response Array ( [code] => 500 [body] => 500 Internal Server Error nginx).

Isso está acontecendo na API Live, ou seja, em produção. Na API de testes este problema não ocorre, nem chegou a ser identificado na homologação.

Obs.: caso o pagamento seja válido (com aprovação do cartão), o retorno é correto e aprova o pagamento.

## Ambiente
* SDK Pagar.me 0.1.6
* Servidor Linux
* PHP 5.5
* Apache 2.2
- MySQL 5.6

## Passos para reproduzir
Basta realizar um pedido e tentar pagar com cartão fictício desses geradores que tem na Internet:
https://www.brasilnutrishop.com.br/

## Resultado esperado
status "acquirer refused”

## Resultado atual
Failed to decode json from response. Response Array ( [code] => 500 [body] => 500 Internal Server Error nginx).

## Screenshots
[se for relevante, inclua uma screenshot]

**Comment by devdrops** [comment]
Fala @dilersik!

Muito obrigado pelo report. Antes, uma dúvida: na issue, a versão do SDK informada é `0.1.6`, é essa mesmo? Pode confirmar por favor?

**Comment by dilersik** [comment]
Segundo o PagarMe.php é api_version = '1';

**Comment by devdrops** [comment]
Opa @dilersik, tudo certo?

A versão contida no branch `V2` não prevê novas alterações, e para todas as integrações, recomendamos usar a versão mais recente (mais detalhes [aqui](https://github.com/pagarme/pagarme-php/blob/V3/README.md)), já estável e pronta para uso.

Contudo, independente da versão do SDK, o problema reportado parece vir da API ao invés deste SDK, portanto vamos reportar isso para o time responsável para validar uma correção o mais breve possível.

Qualquer dúvida, pode comentar nesta mesma issue, ok?

**Comment by dilersik** [comment]
Boa tarde @devdrops  tudo bem?

Mas a documentação oficial no site, em momento algum se refere a essa nova versão. Veja:
https://docs.pagar.me/transactions/
https://docs.pagar.me/api/?php#criando-uma-transacao

Assim fica complicado saber qual utilizar.

A V3 está finalizada? Estável?

Se sim, porque não está na documentação?

Obrigado.

**Comment by devdrops** [comment]
Opa, boa tarde @dilersik!

> Mas a documentação oficial no site, em momento algum se refere a essa nova versão.

Cara, total falha nossa. Estamos reformulando nossa documentação para um novo formato, que está em fase beta ainda, que conta com os exemplos da versão mais recente do SDK. Ainda estamos finalizando essa nova documentação, por isso ainda não se encontra disponível.

> A V3 está finalizada? Estável?

Sim, a V3 já se encontra estável desde Jan/2017 e é hoje a versão mais indicada para integrações com PHP. Toda a documentação dela se encontra neste repositório (na [wiki](https://github.com/pagarme/pagarme-php/wiki/) e no [readme](https://github.com/pagarme/pagarme-php/blob/V3/README.md)). Ela tem toda uma cobertura de testes e traz muito mais recursos de integração do que as versões anteriores.

Consegui te ajudar?

**Comment by dilersik** [comment]
@devdrops boa tarde

Sim, obrigado pelas respostas. Abraço.

**Comment by dilersik** [comment]
@jackperissute e eu ficamos horas para tentar descobrir a causa deste erro 500 do Pagarme.
Depois de muitos testes e eliminando todas as outras possibilidades, notamos que um campo, dentro de metadata, estava sendo passado com codificação diferente de UTF-8.

Provavelmente algum caractere especial gerava um erro no Json CURL que estava sendo enviado ao Pagarme.

O mais impressionante (ou decepcionante) é que não é retornado nada do tipo "Json inválido", "estrutura do Json com problemas", mas simplesmente um erro HTTP 500. :/

Enfim, fica aí a solução se alguém tiver o mesmo problema.

**Comment by felquis** [comment]
@dilersik você consegue passar pra gente qual era a info que vc estava passando pra gente reproduzir?

**Comment by felquis** [comment]
Consegui reproduzir com:

```json
{
	"api_key": "ak_test_never_share_api_keys",
	"amount": 10000000,
	"installments": 12,
	"card_number": "4111111111111111",
	"card_holder_name": "Felquis Gimenes",
	"card_expiration_date": "1225",
	"card_cvv": "777",
	"metadata": {
		"nomeDoCampo": "testeValorDoCampo",
		"asas\": 1234567890
	}
}
```

**Comment by felquis** [comment]
Confirmadissimo!

**Comment by jackperissute** [comment]
@felquis Na realidade nosso erro não era estrutura do JSON, e sim na codificação do conteúdo do JSON.
No caso o texto "Grátis" não estava sendo convertido para UTF8, portanto era enviado em codificação ISO-8859-1.

Segue exemplo:
{
	"api_key": "ak_test_never_share_api_keys",
	"amount": 10000000,
	"installments": 12,
	"card_number": "4111111111111111",
	"card_holder_name": "Felquis Gimenes",
	"card_expiration_date": "1225",
	"card_cvv": "777",
	"metadata": {
		"numero_pedido": "1",
		"Tipo do frete": "Grátis"
	}
}
