### ISSUE TITLE
Remover uso de curl nos testes de aceitação

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-php#197]
## Contexto

Substituir o uso das funções de `curl` contidas nos testes e usar recursos padronizados no projeto, como:

- Guzzle diretamente
- O próprio Client oferecido neste repositório.

Fonte: https://github.com/pagarme/pagarme-php/blob/V3/tests/acceptance/BasicContext.php#L32

## Ambiente

* SDK Pagar.me 3.3.1

## Passos para reproduzir

Substituir as chamadas de funções como `curl_exec` por chamadas pelas ferramentas apontadas.

## Resultado esperado

Não há alteração visível no comportamento dos testes.

**Comment by leonampd** [comment]
Dado que temos uma nova versão do SDK, estou fechado essa issue.
