### ISSUE TITLE
[Documentação] Criação de cartão/transação com card_hash

### ISSUE THREAD

**Issue by andre13pmc** [pagarme/pagarme-php#198]
Seria possível incluir detalhes e exemplos sobre criação de transação e de cartão utilizando o card_hash? 

Não achei nada na atual documentação.

Segue abaixo um esboço inicial de exemplo de criação de um objeto cartão (com card_hash) e em seguida, de uma transação. Seria interessante também mostrar como é possível efetivamente criar um cartão no Pagar.me (fazendo o request para a API e recebendo o card_id no retorno) utilizando card_hash.

$card = new \PagarMe\Sdk\Card\Card(["hash" => "669572_OOK0iKkBl/+oHkR3NfVMzR0y4V37bN3hKAEUsrXV82psVijRaM1xwSyD07QkLE6Ms1+x7Bd+Kk7L7oUNIA9o+AocyHre70QwStMSMmYSsnrgl5ThktBgf+VNXbGR2DganhIVyO8FntvR5UTNtIHOvk+mwzxBYKP8ZgKLkE7ak6kOPiHWDMhkjY/Tc8N9GCbwU4FjxLyeyiuubDdApmRxMM9Mm8sCWMKWwOWjJcCCgb5+E38JLuqj/nO2novbanya6plUAM3kRS7KJQdebaMLLtvfoafbTkF7+RS6nfGvkpYkfMQnwTYnEj9pefmhEgK3xAfUI9t6WoiDOfeE2YzPsw=="]);

	$transaction = $pagarMe->transaction()->creditCardTransaction(
	    $amount,
	    $card,
	    $customer,
	    $installments,
	    $capture,
	    $postbackUrl,
	    $metadata
	);

**Comment by leandrodaf** [comment]
Descrever a funcionalidade card_hash principalmente.

**Comment by piiih** [comment]
@andre13pmc @leandrodaf Peço desculpas pela demora sobre essa issue. Mas segue o link da docs.
https://docs.pagar.me/v2017-07-17/reference#criando-um-cartao
