### ISSUE TITLE
Balance operation de refunds de boleto

### ISSUE THREAD

**Issue by henriquekano** [pagarme/pagarme-php#200]
## Contexto

Ao listar balance operations e um desses é um refund, não é possível investigar o movement_object relacionado, resultando em uma exceção:

## Ambiente

* SDK Pagar.me v3.3.2
* PHP 7.0

## Passos para reproduzir

```php
<?php
	require __DIR__.'/vendor/autoload.php';

	$pagarMe = new \PagarMe\Sdk\PagarMe('MINHA_API_KEY');

	$operationList = $pagarMe->balanceOperation()->getList(1, 100);
	var_dump($operationList);
```
(peça minha api key pra testes)

## Resultado esperado

Lista de balance operations, seja o movement object uma transfer, um payable ou um refund

## Resultado atual

Exceção:
```
Stack trace:
#0 /home/henriquekano/git/pocs/php/vendor/pagarme/pagarme-php/lib/BalanceOperation/OperationBuilder.php(17): PagarMe\Sdk\BalanceOperation\BalanceOperationHandler->buildMovement(Object(stdClass))
#1 /home/henriquekano/git/pocs/php/vendor/pagarme/pagarme-php/lib/BalanceOperation/BalanceOperationHandler.php(30): PagarMe\Sdk\BalanceOperation\BalanceOperationHandler->buildOperation(Object(stdClass))
#2 /home/henriquekano/git/pocs/php/index.php(6): PagarMe\Sdk\BalanceOperation\BalanceOperationHandler->getList(1, 100)
#3 {main}
  thrown in /home/henriquekano/git/pocs/php/vendor/pagarme/pagarme-php/lib/BalanceOperation/OperationBuilder.php on line 39
```

**Comment by leonampd** [comment]
Oi @henriquekano tudo bem?

Dado que temos uma nova versão do [SDK](https://github.com/pagarme/pagarme-php) estou fechando essa issue, tudo bem? Se julgar necessário fique a vontade para abrir essa issue.

**Comment by eluizbr** [comment]
Olá,
Esse problema esta acontecendo com a API em python.
- Crio o pagamento
- Faço o estorno na dashboard
Quando busco o refund, o mesmo retorna um array vazio

Alguma dica?

**Comment by leonampd** [comment]
Fala @eluizbr tudo bom? Eu nem faço mais parte do time mas, acho uma boa você abrir uma issue em https://github.com/pagarme/pagarme-php/issues/200 ou até mesmo entrar em contato com a galera do time de suporte. Eles são fera e acho que por lá é mais eficás pra vc ter ajuda. :wink:
