### ISSUE TITLE
Split com Assinatura

### ISSUE THREAD

**Issue by gstpreira** [pagarme/pagarme-php#201]
## Contexto

Na documentação, é mencionado a possibilidade de fazer uma assinatura com Split, mas não esta implementado essa possibilidade atualmente.

https://docs.pagar.me/v2017-07-17/reference#criando-assinaturas-com-split

## Resultado esperado

Acredito que seria interessante ter a possibilidade de criar uma assinatura com Split

## Resultado atual

Atualmente a lib não comporta o Split com assinatura

## Possível correção

Acredito que a passagem de parâmetros na criação da assinatura possa resolver

@xduh @devdrops @vgsmith

**Comment by vgsmith** [comment]
Boa tarde @gstpreira , como vai?

Realmente o SDK deve cobrir todas as funcionalidades da API. Vamos priorizar esta demanda e retornamos por aqui assim que finalizado.

Caso tenha algum chamado aberto em nosso suporte, por favor me envie o id por aqui.

Abs

**Comment by gstpreira** [comment]
Fala @vgsmith tudo tranquilo ?
Cara acabei de fazer um PR #202 com essa correção, se você puder dar uma olhada e ver se esta tudo correto, estou precisando dessa implementação super rápido, por isso fiz o PR para a implementação  :)

**Comment by gstpreira** [comment]
Alguém consegue revisar o meu PR mencionado a cima ? Estou precisando dessa implementação  :)

**Comment by xduh** [comment]
@gstpreira Obrigado pela contribuição, estamos normalizando os testes do CI, em seguida seguiremos com a revisão do PR descrito.

**Comment by gstpreira** [comment]
Valeu pelo feedback @xduh sabe me dizer se tem algum prazo ? Pois caso demore vou deixar de usar o SDK de vocês e vou usar o meu fork, pois preciso de implementação pois é estratégica no meu negócio  :)

**Comment by vgsmith** [comment]
#202
