### ISSUE TITLE
Não é possível definir uma operação de estorno (refund) e passar o atributo 'async'

### ISSUE THREAD

**Issue by DfKimera** [pagarme/pagarme-php#206]
## Contexto

A função `$transaction->creditCardRefund(CreditCardTransaction $transation, $amount = null)` só aceita os parâmetros `$transaction` e `$amount`. Idealmente, deve ser possível indicar parâmetros opcionais para o método, tal como o `async`.

Isso é importante pois, hoje, é impossível rastrear estornos *parciais* feitos através da SDK PHP. Um estorno parcial não gera alteração de status, e portanto o POSTback da transação não é acionado. Também não se pode ler o status da transação logo após o `creditCardRefund()`, pois por default ele roda de forma assíncrona.

## Possível correção

* **(Recomendado)** Implementar um campo `additional_parameters` para o método `creditCardRefund()`, para que o desenvolvedor possa definir quaisquer outros campos que desejar<sup>1</sup>.
* Implementar o parâmetro opcionais `async` na função `creditCardRefund()`
* Definir o campo `async` como `false` na implementação do método `creditCardRefund()`. Creio ser um default mais apropriado, uma vez que a operação é muito mais administrativa, e não tem impacto direto no fluxo de venda.

_<sup>1</sup> Arrisco dizer que esse campo deveria estar em todas as operações; a API de vocês evolui mais rápido do que o SDK consegue acompanhar, e seria legal dar a flexibilidade aos desenvolvedores de passar campos adicionais sempre que necessário_

**Comment by vgsmith** [comment]
Boa tarde @DfKimera , como vai?

Foi implementado recentemente em nossa API o envio do parâmetro `metadata` nas operações de estorno, exatamente com a intenção de rastrear estornos parciais. Acredito que isso soluciona seu problema, correto?

Esta _feature_ ainda não está em produção, mas o SDK V3 será adequado em breve. Caso tenha interesse, estamos abertos à contribuição também.

Ainda sim, muito obrigado pela sugestão do `additional_parameters`, é uma solução interessante e será discutido com o time. 

Abs

**Comment by DfKimera** [comment]
Na verdade, é até mais simples do que o campo `metadata`.

O campo `async` diz se a operação de estorno será determinística ou não. No meu caso de uso, estou implementando a opção de realizar estornos parciais diretamente no painel do suporte ao cliente. Sem saber se o estorno foi realizado corretamente, não posso seguramente atualizar qual o valor total estornado do pedido no meu sistema (uma vez que o estorno pode falhar e eu não receber a notificação). Ao transformar a operação em síncrona, eu passo a poder ver o status da operação imediatamente.

Idealmente teriamos um POSTback para estornos parciais além dos estornos totais, mas isso é uma mudança que quebraria possivelmente backwards-compatibility com várias pessoas que contam com o POSTback somente em alterações de status.

Vou fazer um pull request só com a adição do campo `async`, tudo bem @vgsmith?

**Comment by leonampd** [comment]
Oi @DfKimera tudo bem?

Dado que temos uma nova versão do [SDK](https://github.com/pagarme/pagarme-php) estou fechando essa issue, tudo bem? Se julgar necessário fique a vontade para abrir essa issue.
