### ISSUE TITLE
external_id is required

### ISSUE THREAD

**Issue by newerton** [pagarme/pagarme-php#208]
## Contexto

Erro ao criar um cliente.

{"errors":[{"type":"validation_error","parameter_name":"customer","message":"child \"external_id\" fails because [\"external_id\" is required]"}],"url":"/customers","method":"post"}

## Ambiente

[caso essa issue se trate de um bug, descreva como é o ambiente que ele ocorre, por exemplo:]

* SDK Pagar.me v3
* Servidor Windows
* PHP 7.1.8
* Apache 2.4
* cacert.pem (atualizada): "curl --remote-name --time-cond cacert.pem https://curl.haxx.se/ca/cacert.pem"
```
$ php -v
PHP 7.1.8 (cli) (built: Aug  1 2017 21:10:46) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
soap
sockets
SPL
standard
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

```
## Passos para reproduzir
```
curl -X POST https://api.pagar.me/1/customers \
-d "api_key=MYSECRETAPIKEY" \
-d "document_number=18152564000105" \
-d "name=nome do cliente" \
-d "email=eee@email.com" \
-d "born_at=13121988" \
-d "gender=M" \
-d "address[street]=rua qualquer" \
-d "address[complementary]=apto" \
-d "address[street_number]=13" \
-d "address[neighborhood]=pinheiros" \
-d "address[city]=sao paulo" \
-d "address[state]=SP" \
-d "address[zipcode]=05444040" \
-d "address[country]=Brasil" \
-d "phone[ddi]=55" \
-d "phone[ddd]=11" \
-d "phone[number]=999887766"
```
## Resultado esperado

Confirmação da criação do Cliente.

## Resultado atual

O erro me informa que esta faltando o external_id.

**Comment by henriquekano** [comment]
Fala @newerton!

Não é um erro da sdk em sí, mas algo específico da última versão da API, onde a interface pública mudou consideravelmente: https://docs.pagar.me/v2017-08-28/reference.

No momento, a sdk de PHP não é compatível com a última versão da API, sendo necessário mudar a versão de sua API usada conversando com o time de relacionamento (relacionamento@pagar.me), se php for um requerimento de seu projeto, ou utilizar as sdks de python (https://github.com/pagarme/pagarme-python) ou js (https://github.com/pagarme/pagarme-js), que aceitam os parâmetros em forma de hash

**Comment by newerton** [comment]
Olá @henriquekano !

Obrigado pela resposta imediata. Acho que conseguir identificar o problema aqui. Testei com outra chave, e funcionou.

Tem algo a ver com a validação da minha conta? Por exemplo assinar o contrato?

**Comment by newerton** [comment]
Só resaltando, eu testei com as versões v3.3.2 e v3.4.0, e retornou o mesmo erro no SDK. E bem provavel que deve ser alguma validação de conta.

**Comment by newerton** [comment]
Mandei e-mail para o suporte, eles identificaram meu problema.

Segue o e-mail:

> Olá Newerton.
> Entendi qual é o problema!
> 
> Como a sua API está na nova versão v2017-08-28, diferente da outra chave ak_test_xxxxxxx​ que está na versão antiga,  existem mais dados a serem enviados para criar um transação, como por exemplo os dados de entrega (shipping​), cobrança (billing​) e produtos (items​) .
> 
> Para uma visão mais ampla de todos os novos atributos que se tornaram obrigatórios , recomendo que você acesse nossa documentação clicando [aqui](https://docs.pagar.me/v2017-08-28/reference#criar-transacao), pois lá você encontra informações sobre cada um deles detalhadamente.
> 
> Vale salientar ainda que nenhuma de nossas bibliotecas é compatível com a versão v2017-08-28, sendo assim a integração da mesma fica por conta de desenvolvimento próprio através de nossos endpoints.
> 
> Faz sentido? Qualquer dúvida, estou à disposição.
> 
> Att.
> Leonardo
