### ISSUE TITLE
Split na Captura

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-php#210]
## Contexto

Quando criada uma transação via _checkout_, não é possível realizar sua captura passando _split_rules_ e _metadata_, como pode ser visualizado [aqui](https://docs.pagar.me/v2017-07-17/docs/realizando-uma-transacao-de-cartao-de-credito#section-captura-com-split-rules-e-metadata
)

## Ambiente

* SDK Pagar.me PHPv3 3.*
* PHP 7.0

## Passos para reproduzir

Utilizar o _checkout_ pagar.me e tentar realizar a captura com _split_rule_.

## Resultado esperado

Captura realizada com divisão de valores realizada pela _split_rule_.

## Resultado atual

Captura realizada sem _split_rule_.

## Possível correção

Ser possível enviar o parâmetro _split_rules_ no ato da captura.
## Screenshots

Se precisar de ajuda em algo fico à disposição.

**Comment by devdrops** [comment]
Fala @murilohns!

Peço que por favor siga o modelo de abertura de issues, conforme descrito no [guia de contribuição](https://github.com/pagarme/pagarme-php/blob/V3/CONTRIBUTING.md) deste repositório. Isso nos ajuda a entender a issue com muito mais detalhes :wink:

**Comment by murilohns** [comment]
#245

**Comment by murilohns** [comment]
resolvido com o #245, _feature_ disponível a partir da versão 3.7.2
