### ISSUE TITLE
Async em transação via boleto bancário

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-php#212]
## Contexto

Atualmente não é possível adicionar a flag async à transações de boleto bancário. Esse parâmetro é necessário para obter a URL do boleto na resposta da requisição.

## Passos para reproduzir

Tente criar uma transação e enviar o parâmetro `async = false` em seu corpo

## Resultado esperado

Obter a URL do boleto

## Resultado atual

Transação retorna com status `processing` , sem boleto_url

## Screenshots
Código: 
![image](https://user-images.githubusercontent.com/18074134/30607219-a4691700-9d4a-11e7-8f92-daa224908906.png)

Resposta:
![image](https://user-images.githubusercontent.com/18074134/30607243-b4b67468-9d4a-11e7-9455-8747f8752417.png)

Se precisarem de ajuda em algo fico à disposição.

**Comment by devdrops** [comment]
@murilohns uma proposta para isso é que a classe `PagarMe\Sdk\Transaction\BoletoTransaction` tenha:

- Atributo `async` ([exemplo](https://github.com/pagarme/pagarme-php/blob/V3/lib/Transaction/CreditCardTransaction.php#L29-L32))
- Método de manipulação desse atributo ([exemplo](https://github.com/pagarme/pagarme-php/blob/V3/lib/Transaction/CreditCardTransaction.php#L88-L96))

Assim ele passa a usar o `extraAttributes` na composição do objeto.

**Comment by devdrops** [comment]
Closed on #214.
