### ISSUE TITLE
Erro simples na documentação

### ISSUE THREAD

**Issue by redhmam** [pagarme/pagarme-php#215]
## Contexto
Ao copiar as instruções da documentação  **planos**, percebi este simples erro.

## Passos para reproduzir

A página com o erro na documentação é a https://github.com/pagarme/pagarme-php/wiki/Planos
Neste exemplo:
```php
/** @var $plan \PagarMe\Sdk\Plan\Plan */
$plan = $pagarMe->plan()->create(
    4990,
    30,
    'Plano Especial',
    0,
    ['**creditt_card**', 'boleto'],
    null,
    1
);
```
## Resultado esperado
```php
/** @var $plan \PagarMe\Sdk\Plan\Plan */
$plan = $pagarMe->plan()->create(
    4990,
    30,
    'Plano Especial',
    0,
    ['**credit_card**', 'boleto'],
    null,
    1
);
```

**Comment by felquis** [comment]
Boa, corrige! Obrigado :D

**Comment by felquis** [comment]
Alias, a documentação "oficial" deve ser essa aqui https://docs.pagar.me/v2017-08-28/reference#criando-planos

Me avise se ela atende os mesmos pontos da documentação que está em nossa Wiki aqui :dancer: :dagger:
