### ISSUE TITLE
Ausência do tipo de conta na documentação da WIKI

### ISSUE THREAD

**Issue by redhmam** [pagarme/pagarme-php#217]
## Contexto

Apesar da variável **type** ser opcional, ela não consta na wiki.

Página que contem a ausência da variável.
https://github.com/pagarme/pagarme-php/wiki/Contas-Banc%C3%A1rias

## Ambiente

![image](https://user-images.githubusercontent.com/3311452/31467517-99e34ed2-aeb0-11e7-9cbf-f0f281e21af5.png)

## Resultado esperado

![image](https://user-images.githubusercontent.com/3311452/31467726-564fe67a-aeb1-11e7-950e-a6ac443166bd.png)

**Comment by felquis** [comment]
Opa, acabei de corrigir! Valeu por avisar.

Usar essas wikis do Github é uma furada, pois não tem como aceitar PR para corrigir este tipo de erro. Documentação em arquivos markdown são bem melhores.

A melhor doc que temos é essa referência https://docs.pagar.me/v2017-08-28/reference#criando-uma-conta-banc%C3%A1ria
