### ISSUE TITLE
Dúvida na listagem de planos

### ISSUE THREAD

**Issue by lucaswillemen** [pagarme/pagarme-php#223]
## Estou tentando capturar os planos cadastrados mas estou tendo um retorno estranho
```
use \PagarMe\Sdk\PagarMe;
class Pagamento extends CI_Controller {
	public function index()
	{
		$pagarMe = new PagarMe('MYAPIKEYTHATIWILLNEVERSHARE');

		/** @var $plans \PagarMe\Sdk\Plan\Plan */
                $plans = $pagarMe->plan()->getList();
                echo "<pre>";
		print_r($plans);
	}
}


```

Me retorna isso -->
```
Array
(
    [0] => PagarMe\Sdk\Plan\Plan Object
        (
            [amount:PagarMe\Sdk\Plan\Plan:private] => 11900
            [id:PagarMe\Sdk\Plan\Plan:private] => 225957
            [days:PagarMe\Sdk\Plan\Plan:private] => 30
            [name:PagarMe\Sdk\Plan\Plan:private] => BitMi Business
            [trialDays:PagarMe\Sdk\Plan\Plan:private] => 0
            [paymentMethods:PagarMe\Sdk\Plan\Plan:private] => Array
                (
                    [0] => credit_card
                )

            [charges:PagarMe\Sdk\Plan\Plan:private] => 
            [installments:PagarMe\Sdk\Plan\Plan:private] => 1
        )

)

```

**Comment by derekstavis** [comment]
Por o que entendi vc quer transformar o objeto retornado pela para JSON, confere?

**Comment by leonampd** [comment]
@lucaswillemen tudo bem?

Pelo output que você forneceu, me parece que não há nada de errado no retorno. Você pode ter mais informações na nossa [documentação](https://docs.pagar.me/reference#objeto-plano). Mas lembre-se, de verificar a versão da sua _API_KEY_

Aproveitando, seria legal que você seguisse o nosso [modelo](https://github.com/pagarme/pagarme-php/blob/V3/.github/ISSUE_TEMPLATE.md) para abertura de issues nas próximas vezes. Ele nos ajuda a entender melhor o problema, por exemplo.

**Comment by vanessasoutoc** [comment]
Estou com o mesmo problema! no retorno eu tento converter pra json é retorna apenas [] pois não consegue converter!!

**Comment by murilohns** [comment]
Olá Vanessa, bom dia.

Você deve acessar os atributos desse método através de seus métodos _getters_.

Então, se você quiser acessar o ID, você deve utilizar o código `$plan->getId();`

**Comment by murilohns** [comment]
Oi @vanessasoutoc e @lucaswillemen, tudo bem?

O problema de vocês foi resolvido? Podemos ajudar em mais algo?

**Comment by vanessasoutoc** [comment]
O meu foi @murilohns .
Obrigado.
