### ISSUE TITLE
Propriedade invoice_reminder do objeto plano

### ISSUE THREAD

**Issue by MarlonEtiene** [pagarme/pagarme-php#225]
## Contexto

Gostaria de saber se existe alguma previsão para ter a propriedade invoice_reminder no objeto plano, tanto na criação quanto na alteração de um plano.

## Ambiente

* SDK Pagar.me 3.4.0
* Servidor Linux
* PHP 7.1.11
* Apache 2.2
* MySQL 5.7.20

**Comment by murilohns** [comment]
adicionado no #250, _feature_ disponível a partir da versão 3.7.2 do SDK.
