### ISSUE TITLE
Pegar ID de conta bancária criada

### ISSUE THREAD

**Issue by Luc45** [pagarme/pagarme-php#233]
## Contexto

Estou tentando criar uma conta bancária e salvar o ID retornado no banco de dados.

## Passos para reproduzir

```
    $bankAccount = $pagarMe->bankAccount()->create(
        $bank_code,
        $agencia,
        $conta,
        $conta_dv,
        $document_number,
        $legal_name,
        $agencia_dv,
        $type
    );
    var_dump($bankAccount); // Isso é um objeto, onde o parâmetro ID, que eu preciso, é privado, e o $pagarMe->bankAccount()->get(); não aceita objetos, apenas IDs
```

## Resultado esperado

Gostaria que o $pagarMe->bankAccount()->get() aceitasse objetos, ou que o $pagarMe->bankAccount()->create() retornasse um ID, ou que o objeto BankAccount tivesse o ID public.

## Resultado atual

O ID é privado e não consigo mandar para o get.

## Possível correção

Eu posso estar fazendo algo errado, vou esperar as respostas.

## Screenshots

!(id conta bancaria pagarme)[https://www.lucasbustamante.com.br/uploads/u/2017/11/dia-24_21h18m32s_chrome.png]

**Comment by dann95** [comment]
Olá, primeiramente não sou do time @Pagarme mas, o que você quer fazer é completamente possível, a visibilidade "private" não afeta o que você precisa, a classe BankAccount que é "fillada" com dados da API, mantém todos os dados como private, porque é uma entidade que representa a resposta da API, logo por segurança deve ser PRIVATE, entretanto todas as properties que ela possui, tem GETTERS, ex do id: https://github.com/pagarme/pagarme-php/blob/V3/lib/BankAccount/BankAccount.php#L81 , logo basta chamar:
```php
    $bankAccount = $pagarMe->bankAccount()->create(
        $bank_code,
        $agencia,
        $conta,
        $conta_dv,
        $document_number,
        $legal_name,
        $agencia_dv,
        $type
    );
    var_dump($bankAccount->getId());
```

att Daniel.

**Comment by Luc45** [comment]
É isso aí Dan, deu certinho, obrigado!

**Comment by dann95** [comment]
de nada, abraço!
