### ISSUE TITLE
Criação de Cartão - Pergunta

### ISSUE THREAD

**Issue by leandrommaia** [pagarme/pagarme-php#234]
Boa tarde pessoal,

Estou tentando criar uma assinatura porém não gostaria de que o cartão fosse armazenado. Para isso tentei usando a seguinte forma: `$card new \PagarMe\Sdk\Card\Card` e na hora de criar a assinatura eu passo esse objeto. Porém não tive sucesso ao realizar isso.

Tentei então criar da forma usual:  `$card = $this->pagarMe->card()->create`. Porém notei que dessa forma eu não posso passar o CVV para testar caso o cartão seja recusado. Ele retorna que a data de expiração é inválida.

Existe alguma forma de criar um cartão sem ser pelo método `$card = $this->pagarMe->card()->create` e que eu possa passar também o CVV para testar cartão recusado?

Estou usando a API V3 PHP.

Obrigado

**Comment by devdrops** [comment]
Fala @leandrommaia, tudo ok?

Cara, pedimos que por favor siga o formato de abertura de issues, conforme o nosso modelo, disponível [aqui](https://github.com/pagarme/pagarme-php/blob/V3/.github/ISSUE_TEMPLATE.md) :wink:

**Comment by leandrommaia** [comment]
## Contexto

Ao criar uma assinatura, criar um cartão e passar um CVV que retorne como **RECUSADO** no status.

## Ambiente

* SDK Pagar.me 3

## Passos para reproduzir

Criar uma assinatura e criar um cartão através do método `$card = $this->pagarMe->card()->create`, porém passar um CVV que retorne como **RECUSADO** o pagamento.

## Resultado esperado

`$subscription->getStatus() = refused`

## Resultado atual

`$subscription->getStatus() = paid`

**Comment by murilohns** [comment]
Fala @leandrommaia, beleza?

Se você tentar criar uma assinatura com cartão inválido, irá dar a seguinte mensagem de erro: "Não foi possível realizar uma transação neste cartão de crédito" e ela não será criada.

Caso você queira simular a recusa de um cartão de crédito, você pode fazer isso com transações, enviando um payload dessa forma:
```
$transaction = $pagarMe->transaction()->creditCardTransaction(
	    $amount,
	    $card,
	    $customer,
	    $installments,
	    $capture,
	    $postbackUrl,
	    $metadata,
    	[
             'async' => false,
             'card_cvv' => '616'
        ]
	);
```
Nota: Uma assinatura nunca alcançará o status `refused`.

Se eu puder ajudar em mais algo fico à disposição :)

**Comment by leandrommaia** [comment]
Opa Murilo obrigado pela ajuda.

Só mais uma questão: caso a assinatura seja com um cartão inválido ela vai retornar essa mensagem de erro na Exception correto?

Em relação ao status `refused` da assinatura, como ficaria o caso por exemplo se o cliente informar os dados do cartão e ele não tiver crédito suficiente para a transação? Vai retornar o mesmo erro do cartão inválido?

Obrigado

**Comment by murilohns** [comment]
Olá @leandrommaia, bom dia :)

Sim, essa mensagem será retornada em uma Exception.

Com relação à assinatura "refused", caso ela esteja sendo criada, ou paga uma de suas cobranças com um cartão inválido, acontecerá a mesma coisa. Irá retornar a mensagem de "Não foi possível realizar uma transação neste cartão de crédito".

Nota: Os possíveis status de uma assinatura são `trialing`, `pending_payment`, `unpaid`, `paid`, `canceled`, `ended`

**Comment by leandrommaia** [comment]
Oi @murilohns bom dia,

Cara me desculpe me expressei mal na segunda pergunta. A dúvida que talvez até você já tenha respondido é o status `refused` na transação do cartão de crédito. Ou seja eu não tenho limite suficiente para o pagamento. 

Aí nesse cenário então vou ter a mensagem de "Não foi possível realizar uma transação neste cartão de crédito" na exception?

Muito obrigado.

**Comment by murilohns** [comment]
Isso mesmo @leandrommaia :)

**Comment by leandrommaia** [comment]
Valeu cara, muito obrigado.
