### ISSUE TITLE
Como obter lista de payables de uma transação?

### ISSUE THREAD

**Issue by moirrer** [pagarme/pagarme-php#236]
Segundo a documentação do Pagarme (https://docs.pagar.me/v2013-03-01/reference#retornando-um-transa%C3%A7%C3%A3o) é possível puxar uma lista de todos os 'payables' de uma transação:

    Pagarme::setApiKey("SUA_API_KEY");
    $transaction = PagarMe_Payable::findAllByTransactionId($transaction_id);
    print_r($transaction);

Existe uma maneira de puxar esses payables por essa lib?
Só encontrei um metodo para puxar todos os payables usando de paginação, mas sem um filtro por transação.

**Comment by leonardo-barbosa** [comment]
Olá @moirrer , tudo certo?

Caso esteja utilizando nosso SDK de PHP v2 (branch `master`), você pode realizar essa busca da mesma forma que nos enviou acima:
```php
<?php
    require("vendor/pagarme/pagarme-php/Pagarme.php");

    Pagarme::setApiKey("SUA_API_KEY");

    $transaction = PagarMe_Payable::findAllByTransactionId(ID_DA_TRANSAÇÃO);

    print_r($transaction);
?>
```
Porém, caso esteja utilizando a branch `V3`, ainda não possuímos essa funcionalidade nesta versão.

Qualquer dúvida, estamos aí!

Abraços.

**Comment by moirrer** [comment]
Pois é, estou usando o 3.3.
Acabei fazendo por cURl, já deixo ai pra se mais alguém tiver necessidade até que a implementação fique disponível:

/**
     * Metodo para fazer chamadas cUrl para o pagarme
     * @param String $url           Url conforme documentacao pagarme - https://docs.pagar.me/v2013-03-01/
     * @return JsonObject
     */
    private function pagarmeCurlJson($url){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "api_key=".$API_KEY);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
        $headers = array();
        $headers[] = "Content-Type: application/x-www-form-urlencoded";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $result = curl_exec($ch);
        curl_close($ch);
        return json_decode($result);
    }
    
    /**
     * Retorna todos os registros de pagamentos para uma transacao
     * @param int $transaction_id           Id da transacao no pagarme
     * @return JsonObject
     */
    public function getPayablesPorTransacao($transaction_id){
        $url = 'https://api.pagar.me/1/transactions/'.$transaction_id.'/payables';
        return $this->pagarmeCurlJson($url);
    }

$payables = $this->getPayablesPorTransacao(ID_TRANSACAO);

**Comment by KennedyTedesco** [comment]
A quem se interessar, essa feature foi implementada na versão:

https://github.com/pagarme/pagarme-php/releases/tag/v3.7.3

```php
$payables = $this->pagarMe->transaction()->payables($transactionId);
```
