### ISSUE TITLE
Missing README instructions

### ISSUE THREAD

**Issue by danjesus** [pagarme/pagarme-php#24]
Lack installation instructions and tips on how to contribute to the project.

**Comment by jfoliveira** [comment]
+1

**Comment by brunoberte** [comment]
+1

**Comment by maracaipe** [comment]
+1

**Comment by armandoleite** [comment]
+1

**Comment by ricardotulio** [comment]
The #V2 has been deprecated since the release of V3 and this issue will be resolved in the #V3.
