### ISSUE TITLE
Erro pedindo parâmetro "type" utilizando o boleto transaction

### ISSUE THREAD

**Issue by raphaellmendonca** [pagarme/pagarme-php#241]
## Contexto

Ao utilizar a função boletoTransaction da SDK V3, estamos recebendo o erro que o parâmetro Type não está sendo enviado, sendo que, de acordo com a Wiki, este parâmetro não é necessário.

## Ambiente

* SDK Pagar.me V3
* Servidor Linux
* PHP 7.0
* NGIX 1.12.2
* MySQL Ver 14.14 Distrib 5.6.38

## Passos para reproduzir

Criamos uma chamada padrão, utilizando as informações da Wiki:

```
$pagarMe = new \PagarMe\Sdk\PagarMe(#NOSSA_CHAVE_AQUI#);

$addressData = [
	'street' => 'Rua do Arouche',
	'streetNumber' => '23',
	'neighborhood' => 'República',
	'zipcode' => '01219-001',
	'complementary' => '6º Andar',
	'city' => 'São Paulo',
	'state' => 'SP',
	'country' => 'BR'
];

$address = new \PagarMe\Sdk\Customer\Address($addressData);

$phoneData = [
	'ddd' => '11',
	'number' => '23456789',
	'ddi' => '55',
];

$phone = new \PagarMe\Sdk\Customer\Phone($phoneData);

$customerData = [
    'name' => 'John Dove',
    'email' => 'john@site.com',
    'document_number' => '09130141095',
    'address' => $address,
    'phone' => $phone,
    'born_at' => '15021994',
    'gender' => 'M'
];

$customer = new \PagarMe\Sdk\Customer\Customer($customerData);

$transaction = $pagarMe->transaction()->boletoTransaction(
    1000,
    $customer,
    'http://requestb.in/pkt7pgpk',
    ['idProduto' => 13933139]
);

```
O JSON gerado pela SDK com as informações acima é o seguinte:

```
{
  "amount": 1000,
  "payment_method": "boleto",
  "postback_url": "http:\/\/requestb.in\/pkt7pgpk",
  "metadata": {
    "idProduto": 13933139
  },
  "customer": {
    "name": "John Dove",
    "document_number": "09130141095",
    "email": "john@site.com",
    "sex": "M",
    "born_at": "15021994",
    "address": {
      "street": "Rua do Arouche",
      "street_number": "23",
      "complementary": "6\u00ba Andar",
      "neighborhood": "Rep\u00fablica",
      "zipcode": "01219-001"
    },
    "phone": {
      "number": "23456789",
      "ddd": "11",
      "ddi": "55"
    }
  },
  "boleto_expiration_date": null,
  "async": null,
  "boleto_instructions": null,
  "api_key": "#NOSSA_CHAVE_AQUI#"
}
```

## Resultado esperado

Transação completa

## Resultado atual

Estamos recebendo o retorno:

`"{"errors":[{"type":"validation_error","parameter_name":"customer","message":"child \"type\" fails because [\"type\" is required]"}],"url":"\/transactions","method":"post"}"`

## Possível correção

Mudamos o core da SDK inserindo o "type", então ele dá o mesmo erro acima, só que com "documents". Adicionando o "documents", ele pede para tirar "address", "sex", "phone", "document_number" etc.

Analisando a documentação da API: https://docs.pagar.me/docs/realizando-uma-transacao-de-boleto-bancario notamos a existência de duas formas de chamar o charge do boleto, sendo o primeiro contendo o type e o documents e o segundo (com dados completos), contendo a forma como a SDK está fazendo.

Creio que é necessário indicar como usar a segunda forma que é indicada na documentação ou mesmo fazer com que a API aceite o formato que a SDK V3 envie.

**Comment by murilohns** [comment]
Fala @raphaellmendonca, beleza?

Esse erro ocorre porque sua versão de API é a 2018-08-28, na qual essa SDK(v3) não é compatível. Você pode confirmar essa informação acessando sua [dashboard](dashboard.pagar.me).

Pra que você possa integrar sem problemas com o Pagar.me utilizando essa SDK, peço que envie um e-mail para relacionamento@pagar.me, de seu e-mail cadastrado na [dashboard](dashboard.pagar.me) solicitando a alteração de sua chave de API para a versão 2017-07-17.

Essa é a solução mais rápida enquanto a SDK não é compatível com a nova versão de API do Pagar.me.

Se eu puder ajudar em mais algo fico à disposição =)

Abraços,

**Comment by raphaellmendonca** [comment]
Olá @murilohns! Obrigado pela pronta resposta!
Vou mandar o e-mail solicitado sim, mas existe o pensamento de atualizar a SDK para a nova versão?

Obs: Acho que você errou ali na versão, é 2017-08-28 ;)

**Comment by murilohns** [comment]
Olá @raphaellmendonca ,

Errei a data mesmo xP

Sim, há o pensamento de atualizar a SDK, mas não temos previsão de quando a atualização estará pronta =(

**Comment by raphaellmendonca** [comment]
Beleza, @murilohns 
Fazendo o downgrade da API para a versão 2017-07-17, o SDK v3 funcionou.
