### ISSUE TITLE
Complementos para a lib [dúvidas]

### ISSUE THREAD

**Issue by ramiresGomes** [pagarme/pagarme-php#242]
## Anti-fraude

A lib tem a implementação do verificador anti-fraude contudo para o mesmo funcionar é preciso informar os produtos/items da transação, entretanto não há possibilidade de envio de produtos/items no momento da criação de transação, seja por cartão de crédito seja por boleto. (Existe alguma solução para isso já implementado que não me atentei ou em desenvolvimento?)

## Custo de envio
Da mesma forma do item anterior, no momento da criação da transação não há possibilidade de envio dos dados de envio dos produtos comprados nem mesmo possibilidade de informar o custo do envio/frete, forçando enviar o custo de envio somado com valor da compra. (Existe alguma solução para isso já implementado que não me atentei ou em desenvolvimento?)

**Comment by henriquekano** [comment]
Fala @ramiresGomes, Beleza?

Sobre o antifraude:
Na versão mais atual da sdk, ela adere às versões 2017-07 e 2013-03, que não pediam dados de produtos. No caso da versão mais atual da API web, 2017-08, não há como usar a sdk  para consumí-la.

Sobre o custo de envio:
Da maneira que a API web funciona, ela apenas vê um valor que a aplicação a consumindo passa. Então, assim como você notou, fica a cargo de sua aplicação calcular o frete, juros e descontos para passar o valor final da compra à API web e, consequentemente, à SDK.

**Comment by ramiresGomes** [comment]
@henriquekano Desculpe não ter respondido. 

Muito obrigado pelo seu retorno, foram exatamente as informações que precisava.
