### ISSUE TITLE
Symfony Security Check Report

### ISSUE THREAD

**Issue by matheusfaustino** [pagarme/pagarme-php#246]
## Contexto

Eu estou usando o Symfony Security Check Report, que verifica se os pacotes utilizados possuem algum problema de segurança, para consolidar as versões das third parties usadas no software da empresa.

Recentemente, o teste esta retornando o seguinte texto:

>  [ERROR] 1 packages have known vulnerabilities.                                 
> pagarme/pagarme-php (v3.7.0)
> ----------------------------
>  * (no CVE ID): Padding Oracle Vulnerability in RSA Encryption https://github.com/pagarme/pagarme-php/issues/29

E gostaria de saber se vocês estão cientes disso e se existe algo que eu possa fazer para ajudar nisso, se possível. 

Agradeço pela atenção.

Qualquer coisa esta a disposição.

Att,

## Ambiente

Composer version 1.6.3 2018-01-31 16:28:17
PHP 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:26:45) ( NTS )

## Passos para reproduzir

A Issue esta aqui: https://github.com/pagarme/pagarme-php/issues/29

**Comment by leonampd** [comment]
@matheusfaustino tudo bem?

Antes de mais nada obrigado por ter aberto essa issue. Nós estávamos sabendo sim e já analisamos o que ocorreu. Nosso time está trabalhando para remover esse report da v3 já que o problema só existe na v1 do nosso sdk.

Vamos manter essa issue aberta e, assim que resolvido atualizamos aqui també, ok?

Mais uma vez obrigado!

**Comment by leonampd** [comment]
https://github.com/FriendsOfPHP/security-advisories/pull/261

**Comment by leonampd** [comment]
@matheusfaustino tdo bem? Apenas para dar um retorno: semana passada abri um pr que corrige o range de versões com vulnerabilidade. O problema reportado só aparece nas versões 1 e 2 desse SDK e não na 3 que a mais atual e estável.

Estou fechando essa issue, mas fique à vontade pra reabrir caso julgue necessário e MUITO obrigado pelo aviso.

**Comment by matheusfaustino** [comment]
Ola @leonampd, obrigado pela resposta rápida e prontidão. Desculpa a demora, estava na PHPExperience. Sem problemas, vou ficar de olho e a qualquer coisa eu aviso vocês e se puder ja faço uma PR. Vlw pelo trabalho. 

Abraços.

**Comment by leonampd** [comment]
@matheusfaustino obrigado pelo feedback! Precisando de algo é só dizer!
