### ISSUE TITLE
Erro no nome do parametro do postback url da transação

### ISSUE THREAD

**Issue by sandrocavalcanti** [pagarme/pagarme-php#253]
Existe um erro no nome do parâmetro da url de postback na criação da transação pelo arquivo TransactionHandler.php

$transactionData = array_merge(
            [
                'amount'      => $amount,
                'customer'    => $customer,
                **'postbackUrl' => $postBackUrl,**
                'metadata'    => $metadata
            ],
            $extraAttributes
        );

**Onde o 'postbackUrl' => $postBackUrl, deveria ser 'postback_url' => $postBackUrl**

Devido a isto, não é possível receber postback de transações quando o cliente realiza o pagamento.

**Comment by murilohns** [comment]
Olá Sandro, bom dia.

Realizei alguns testes e _postback_url_ é enviada normalmente nessa SDK.

Pode me enviar um exemplo de código que você está utilizando?

**Comment by sandrocavalcanti** [comment]
Olá Murilo, boa tarde.

Segue código do arquivo TransactionHandler.php



O parametro da url do postback está correto mesmo?
Nenhuma de nossas transações estão sendo gravadas com ele já as assinaturas
estão.

Att,

Sandro Cavalcanti

2018-03-20 11:30 GMT-03:00 Murilo Henrique Nascimento Souza <
notifications@github.com>:

**Comment by sandrocavalcanti** [comment]
Ressalto Murilo que a nossa transação é uma assinatura de boleto.

Att,

Sandro Cavalcanti

2018-03-20 13:45 GMT-03:00 Sandro Cavalcanti <sandrocavalcanti@gmail.com>:

**Comment by murilohns** [comment]
fala @sandrocavalcanti, seu código não chegou =/

Pra ele funcionar, apenas certifique-se que a assinatura de sua chamada está certa, sendo deixa dessa maneira:
```php
$transaction = $pagarMe->transaction()->boletoTransaction(
    $amount,
    $customer,
    $postbackUrl,
    $metadata,
    $extraAttributes
);
```

**Comment by sandrocavalcanti** [comment]
Olá Murilo.

Como nós estamos trabalhando com assinaturas, teria como a assinatura ir
com o postback e o boleto não, caso fosse erro de implementação?

Att,

Sandro Cavalcanti

**Comment by murilohns** [comment]
Fala @sandrocavalcanti,

Se vocês estão criando assinaturas, dessa maneira:

```php
$subscription = $pagarMe->subscription()->createBoletoSubscription(
        $plan,
        $customer,
        $postbackUrl,
        $metadata,
        $extraAttributes = []
    )
```

a postback_url ficará atrelada à assinatura, e não à transação.

Então, quando o boleto for pago, será enviado um postback para a URL declarada no parâmetro postbackUrl, notificando sua plataforma sobre a atualização da assinatura

**Comment by sandrocavalcanti** [comment]
Olá Murilo.

Pronto, exatamente isto não está ocorrendo.
Meus clientes estão pagando e o pagarme não envia o postback da transação.
Segue um ID de exemplo [35904681], você verá que a transação não tem url de
postback mas a assinatura sim.
Não existe nenhum postback relacionado a este pagamento.


Att,

Sandro Cavalcanti

2018-03-20 15:09 GMT-03:00 Murilo Henrique Nascimento Souza <
notifications@github.com>:

**Comment by murilohns** [comment]
fala @sandrocavalcanti,

O _postback_ enviado é quando o status da assinatura for atualizado.
Em caso de boletos pagos, o status da assinatura será atualizado para _paid_ e será disparado um postback para seu site.

Então neste caso, ao receber o postback, você deverá liberar o acesso à assinatura ao seu cliente. 

Transações de assinatura não possuem postback

**Comment by sandrocavalcanti** [comment]
Ok Murilo, muito obrigado pelo feedback.

Vamos revisar todo o codigo de nosso postback para encontrar a falha.
Agradecemos pelo atendimento.

Att,

Sandro Cavalcanti

2018-03-20 15:42 GMT-03:00 Murilo Henrique Nascimento Souza <
notifications@github.com>:

**Comment by piiih** [comment]
@sandrocavalcanti Olá,

A parte que você falo do `postbackUrl` não está errada pelo seguinte motivo. Aquele array é enviado para o método `send` dessa classe: https://github.com/pagarme/pagarme-php/blob/V3/lib/Client.php

Nesse método `send` é chamado um outro método `buildRequest` que irá pegar as informações da request utilizando um `getPayload` que se encontra no arquivo:
https://github.com/pagarme/pagarme-php/blob/V3/lib/Transaction/Request/TransactionCreate.php

Esse `getPayload` faz o tratamento dos nomes colocando o nome `postback_url` certinho ;)

**Comment by sandrocavalcanti** [comment]
Olá Philipe, boa tarde.

Agradeço pelo pronto feedback, vcs são ótimos.
Segue o baile por aqui para encontrar as bruxas.
Grande abraço.

Att,

Sandro Cavalcanti

2018-03-20 15:55 GMT-03:00 Philipe Gouveia Paixão <notifications@github.com>
:
