### ISSUE TITLE
Recebedor > Metadata

### ISSUE THREAD

**Issue by mhbssilva** [pagarme/pagarme-php#259]
## Contexto

Apesar de a API do Pagar.me permitir a inserção/obtenção do campo **metadata**, através do projeto pagarme-php isto não é possível. Os métodos de Recebedor poderiam ser aprimorados para incluir também este atributo, que é muito importante.

## Ambiente

* SDK Pagar.me V3

## Passos para reproduzir

Basta buscar ou inserir um Recebedor para notar que não é possível inserir ou obter os dados de metadata.

## Resultado esperado

Exibir o atributo **metadata** no retorno de uma requisição e permitir sua inserção no cadastro de Recebedor.

## Resultado atual

Todos os atributos de Recebedor com exceção do **metadata** são exibidos/possíveis de alteração.

**Comment by leonampd** [comment]
@mhbssilva tudo bem?

Estou fechando essa issue dado que, agora na versão mais recente do SDK todos os campos são retornados no payload.
