### ISSUE TITLE
SDK V3 - Migração para o protocolo TLS.12

### ISSUE THREAD

**Issue by sotnaspina** [pagarme/pagarme-php#262]
## Contexto

Recebi um e-mail sobre a "Migração para o protocolo TLS.12" e gostaria de saber quando terá uma atualização referente a isso para o SDK V3.

Grato!

## Ambiente

* SDK Pagar.me V3

## Resultado esperado

SDK Pagar.me V3 com o protocolo TLS.12

**Comment by murilohns** [comment]
Olá @sotnaspina, tudo bem?

Você deve verificar se seu servidor possui os requisitos para integração com o protocolo TLS 1.2

Os requisitos são:

* Versão do PHP: >= 5.3 
* Versão da biblioteca cURL: >= 7.34.0
* Versão da biblioteca OpenSSL: >= 1.0.1c

Para identificar as versões desses requisitos em seu sistema, você pode seguir o passo-a-passo abaixo:

1. OpenSSL instalado em seu SO: 
    - Execute o comando `openssl version`.
1. OpenSSL que seu PHP está utilizando:
    - Procure essa informação dentro do arquivo `php.ini`.
1. Para encontrar a versão do OpenSSL de seu cURL, execute o comando abaixo em seu servidor
    ```
    php -r 'echo json_encode(curl_version(), JSON_PRETTY_PRINT);'
    ```

**Comment by thiagoreis** [comment]
@murilohns ,
Fiz as verificações mencionadas. O meu servidor atende aos requisitos.
só teve um detalhe na versão da biblioteca OpenSSL.
no meu caso retornou "OpenSSL\/1.0.1f",  
essa versão com o "f" no final também é suportada?

**Comment by murilohns** [comment]
Olá @thiagoreis,

A versão 1.0.1f é maior que a 1.0.1c, como você pode conferir [nesse link](https://www.openssl.org/source/old/1.1.0/)

Então acredito que esteja tudo certo com seu servidor =)

**Comment by thiagoreis** [comment]
Opa @murilohns 
dei uma conferida no link, não tinha me atentado que a letra faz parte do versionamento. 
a princípio está tudo certo sim.
Obrigado!
