### ISSUE TITLE
Erro ao utilizar método createFromHash

### ISSUE THREAD

**Issue by lucasmaier** [pagarme/pagarme-php#273]
## Contexto

Ao utilizar o método createFromHash, SEMPRE é retornado um erro da API do pagar.me .... Estou tentando criar um cartão pelo hash e não consigo.

O hash é gerado pelo pagarme.js corretamente, as chaves estão corretas. Utilizei o meu próprio cartão para garantir que é um cartão válido, porém sempre é retornado o seguinte erro:

{"errors":[{"type":"invalid_parameter","parameter_name":"card_hash","message":"card_hash inválido. Para mais informações, consulte nossa documentação em https://pagar.me/docs."}],"url":"/cards","method":"post"}

Alguém está utilizando este método recentemente?

**Comment by murilohns** [comment]
fala @lucasmaier , tudo bem?

O card_hash tem 2 premissa:
1. Só pode ser usado 1x
2. Só dura 5 minutos

Se uma dessas regras for quebrada, esse erro ocorrerá. Você está utilizando ele em outra parte de seu código para fazer algo no Pagar.me? Por exemplo: criar transação, ou assinatura

**Comment by lucasmaier** [comment]
Beleza @murilohns .. valeu pela resposta.

Então, eu li sobre essas premissas e não estou quebrando elas. Estou apenas tentando gerar um cartão. Sem criar transação e nem assinatura.

Não sei mais oq fazer rs!... Estou pensando em postar os dados do cartão e gravar pelo create "normal" sem o hash... Mas aí ficar trafegando os dados do cartão sem criptografia é uma péssima prática, correto?

**Comment by lucasmaier** [comment]
@murilohns 

Retomei aqui o projeto que estava desenvolvendo e consegui utilizar normalmente o método createFromHash agora!

Está tudo certo, suas orientações foram precisas! 

Valeu
