### ISSUE TITLE
Cliente duplicado

### ISSUE THREAD

**Issue by sotnaspina** [pagarme/pagarme-php#274]
## Contexto

Primeiramente faço uma requisição para buscar os dados do Cliente (caso o Id dele estiver no banco de dados), se não existir faço outra requisição para salvar.

## Ambiente

[caso essa issue se trate de um bug, descreva como é o ambiente que ele ocorre, por exemplo:]

* SDK Pagar.me 3
* API 2017-07-17

## Passos para reproduzir
```
$id = 11222;
if($id)
$customer = $pagarme->customer()->get($id);
else
$customer = $pagarMe->customer()->create(
    'John Dove',
    'john@site.com',
    '09130141095',
    /** @var $address \PagarMe\Sdk\Customer\Address */
    $address,
    /** @var $phone \PagarMe\Sdk\Customer\Phone */
    $phone,
    '15021994',
    'M'
);
```
depois
```
$subscription = $pagarMe->subscription()->createCardSubscription(
    /** @var $plan \PagarMe\Sdk\Plan\Plan */
    $plan,
    /** @var $card \PagarMe\Sdk\Card\Card */
    $card,
    $customer,
    'http://requestb.in/zyn5obzy',
    ['idProduto' => 13933139]
);
```
## Resultado esperado

Salvar único cliente no painel Pagar.me e a assinatura

## Resultado atual

Duplica o cliente no painel do Pagar.me

**Comment by murilohns** [comment]
fala @sotnaspina, tudo bem?

Não entendi se é no `if` ou no `else` que o cliente é duplicado, mas caso seja no `else`, esse é comportamento correto, não? (criar outro customer)

Também gostaria de pedir a versão da SDK que você está utilizando, sabe me informar?

**Comment by BM9MobileBrasil** [comment]
Aqui, faço via CURL mas acredito que o propósito seja o mesmo:
Ao invés de pegar o usuario pelo endpoint Customer, eu pego o ID de cadastro dele no pagarme que está no meu banco de dados e monto um array manual com os dados básicos, como segue:

```
$pagar = [
             "api_key"                         => API_PAGARME,
             "card_number"               => $dados->numero,
             "card_cvv"                      => $dados->cvv,
             "card_expiration_date"  => $dados->mesano,
             "card_holder_name"      => $dados->nome,
             "customer"                     =>[
                    'id'                                 => $usuario->id_pagarme,
                    'external_id'                  => $usuario->id,
                    'name'                            => $usuario->nome,
                    "type"                            => "individual",
                    "country"                      => "br",
                    "document_number"   => $usuario->cpf,
                    'email'                           => $usuario->email,
                    "phone_numbers"        => [
                        '+55'.$usuario->celular
                    ]
                ]...
```

Aí parou de duplicar...

**Comment by murilohns** [comment]
fala @BM9MobileBrasil, a partir da versão 3.7.0 da SDK já deveria ser possível enviar o customer, sem duplicação da forma vocês estão querendo

Qual a versão da SDK de vocês?

PR que deveria ter corrigido isso: https://github.com/pagarme/pagarme-php/pull/244

**Comment by murilohns** [comment]
fala @BM9MobileBrasil, a partir da versão 3.7.0 da SDK já deveria ser possível enviar o customer, sem duplicação da forma vocês estão querendo

Qual a versão da SDK de vocês?

PR que deveria ter corrigido isso: https://github.com/pagarme/pagarme-php/pull/244

**Comment by BM9MobileBrasil** [comment]
@murilohns por esses problemas com a SDK nós passamos a utilizar grande parte dos procedimentos via cURL mesmo...
Agora estamos migrando nossos projetos para Laravel e decidimos utilizar apenas a SDK para realizar os trabalhos, mesmo que para isso seja necessário criar um fork caso a galera segure os pulls.

obrigado amigo!

**Comment by leonampd** [comment]
@marcelotadeujr ainda está enfrentando esse problema? Se sim, fique a vontade pra reabrir a issue se julgar necessário, ok?
