### ISSUE TITLE
Pesquisar transações por status

### ISSUE THREAD

**Issue by albertoaguiar** [pagarme/pagarme-php#275]
## [PERGUNTA]
Na documentação que tem no site (https://docs.pagar.me/v2017-08-28/reference#retornando-transa%C3%A7%C3%B5es) existe a possibilidade de recuperar as transações por status, pois não consta aqui na API. Existe, de fato, essa possibilidade?
Pois quando eu insero o status, ele me retorna todas as transações do mesmo jeito.

Ex.:
`$this->pagarme->transaction()->getList($page, $count, 'paid');`

**Comment by murilohns** [comment]
Olá @albertoaguiar, pela API é possível fazer esse filtro, mas com a SDK não dá.

O ponto é que os únicos parâmetros mandados na requisição de busca de transações são `page` e `count`, como você pode ver nesse [código](https://github.com/pagarme/pagarme-php/blob/V3/lib/Transaction/Request/TransactionList.php#L7)

Pela API, você pode filtrar dessa maneira: https://api.pagar.me/1/transactions?api_key=SUA_CHAVE_DE_API&status=paid

Uma alternativa para esse problema é utilizar o próprio [cUrl](http://php.net/manual/pt_BR/book.curl.php) para fazer essa busca.

Nota: Não divulgue sua chave de API para ninguém.

Se tiver dúvida em algo é só falar =D

**Comment by murilohns** [comment]
Olá @albertoaguiar , irei fechar essa issue, mas caso precise, pode reabri-la, ok?
