### ISSUE TITLE
Falha ao obter Customers cadastrados sem Endereço

### ISSUE THREAD

**Issue by marcelotadeujr** [pagarme/pagarme-php#278]
## Contexto

Temos clientes cadastrados na API sem endereços, e ao tentar obter a lista de customers ou um customer específico via SDK, a SDK retorna erro "Undefined offset: 0" na trait CustomerBuilder, devido ao trecho tentar criar um address/phone acessando a posição zero (que não existe) do array.

## Ambiente

[caso essa issue se trate de um bug, descreva como é o ambiente que ele ocorre, por exemplo:]

* SDK Pagar.me v3
* AWS EC2
* PHP 7.1
* Apache 2.2

## Passos para reproduzir

1 - Criar um customer sem endereço via cURL:
        
```
        $customer = [
            "api_key"       => env("PAGARME_API_KEY"),
            "external_id"   => (string)$this->usuario->usuario_id,
            "name"          => $this->usuario->usuario_nome,
            "type"          => "individual",
            "country"       => "br",
            "documents"     => [
                [
                    "type"    => "cpf",
                    "number"  => $this->cartao["cpf"]
                ],
            ],
            "email"         => $this->usuario->usuario_email,
            "phone_numbers" => [
                "+55".$this->usuario->usuario_celular
            ]
        ];
        
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_HTTPHEADER,       ["Content-Type: application/json"]);
        curl_setopt($curl, CURLOPT_URL,              "https://api.pagar.me/1/customers");
        curl_setopt($curl, CURLOPT_POST,             1);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER,   1);
        curl_setopt($curl, CURLOPT_USERAGENT,        "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36");
        curl_setopt($curl, CURLOPT_POSTFIELDS,       json_encode($customer));
        $resultado  = curl_exec($curl);
        $resultado  = json_decode($resultado);  
        var_dump($resultado); 
```

2 - Consultar via SDK o customer recém cadastrado

`$pagarMe->customer()->get(ID_DO_CUSTOMER);`
ou
`$pagarMe->customer()->getList(0, 15);`

## Resultado esperado

Obter a listagem dos clientes ou cliente específico através de sua ID.

## Resultado atual

`Error: Undefined offset: 0`

## Possível correção

No arquivo "pagarme-php/lib/Customer/CustomerBuilder.php", no metodo buildCustomer($customerData), verificar se o sizeof do array é maior que zero antes de tentar criar os objetos Address e Phone acessando a posição zero do array.

````
private function buildCustomer($customerData)
    {
        //Checar array antes de criar objeto address
        if(sizeof($customerData->addresses)>0){
            $customerData->address = new Address(
                get_object_vars($customerData->addresses[0])
            );
        }

        //Checar tamanho antes de criar objeto phone
        if(sizeof($customerData->phones)>0){
            $customerData->phone = new Phone($customerData->phones[0]);
        }

        $customerData->date_created = new \DateTime(
            $customerData->date_created
        );

        return new Customer(get_object_vars($customerData));
    }
````

**Comment by murilohns** [comment]
corrigido no PR #306

a _feature_ pode ser utilizada a partir da versão 3.7.10 da SDK =)
