### ISSUE TITLE
Enviar soft_descriptor em assinatura

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-php#282]
## Contexto

Atualmente, na SDK de PHPv3 não é possível enviar o parâmetro `soft_descriptor` na criação de assinaturas.

## Ambiente

[caso essa issue se trate de um bug, descreva como é o ambiente que ele ocorre, por exemplo:]

* SDK Pagar.me 3.7.9

## Possível correção

Adicionar o parâmetro `soft_descriptor` no [extraAttributes](https://github.com/pagarme/pagarme-php/blob/V3/lib/Subscription/Request/SubscriptionCreate.php#L97) de assinaturas de boleto e de cartão de crédito

**Comment by leonampd** [comment]
Dado que temos uma nova versão do [SDK](https://github.com/pagarme/pagarme-php) estou fechando essa issue, tudo bem?
