### ISSUE TITLE
Dúvida de integração do checkout transparente

### ISSUE THREAD

**Issue by rodolfobarretoweb** [pagarme/pagarme-php#294]
## Contexto

Bom dia, estou tentando fazer funcionar o checkout transparente com o sdk php de vocês, porém no exemplo do código php no checkout transparente parece bem destoante em relação ao que vocês possuem na documentação do SDK.

Documentação checkout transparente:
```
require("pagarme-php/Pagarme.php");
Pagarme::setApiKey("ak_test_grXijQ4GicOa2BLGZrDRTR5qNQxJW0");

$transaction = PagarMe_Transaction::findById("TOKEN");
$transaction->capture(1000);
```

Eu já consigo gerar o token mas não consigo dar continuidade visto que na documentação do SDK eu não consegui achar nenhum exemplo que desse a entender que substitui esse da documentação do checkout transparente.

Versão utilizada do sdk: "pagarme/pagarme-php": "3.7.9"

----------------------------

Consegui localizar o exemplo na versão mais atual. Falha minha.

```
<?php require __DIR__.'/vendor/autoload.php';
	$pagarMe = new \PagarMe\Sdk\PagarMe('SUA_API_KEY');
  $amountToCapture = 1000;
  $transaction = $pagarMe->transaction()->get("TOKEN GERADO");
  $transaction = $pagarMe->transaction()->capture(
    $transaction,
    $amountToCapture
  ); 
```

**Comment by jonatasmaxi** [comment]
Olá @rodolfobarretoweb tudo bom?

Meu nome é Jonatas e faço parte da equipe de suporte técnico do Pagar.me. 

Ainda precisa de ajuda?  Qualquer coisa estamos por aqui.

**Comment by rodolfobarretoweb** [comment]
Obrigado, pode fechar a issue.
