### ISSUE TITLE
Contrato do método get de endpoints

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-php#302]
## Contexto

Documentando a nova versão do SDK observei que o método `Plans::get` e todos os outros presentes nos demais endpoints recebem um _array_ `$payload` como parâmetro. Estes métodos por sua vez chamam o método `details` em `Routes` enviando como parâmetro `$payload['id']`. Diante disso pergunto: dado que que nestes casos em que o objetivo é recuperar um registro específico e onde a única maneira de se fazer isso é somente o `id` do registro, porquê não enviar um inteiro/string como parâmetro para os métodos `get` dos endpoints?

Exemplo:

```php
<?php
$plan = $pagarme->plans()->get(['id' => '123456']);
```

O que o método executa:

```
<?php

return $this->client->request(
    self::GET,
    Routes::plans()->details($payload['id'])
);
```

Porque não algo assim:

```php
<?php
$plan = $pagarme->plans()->get('123456');
```

O que o método poderia executar:

```
<?php
/**
     * @param string $id
     *
     * @return \ArrayObject
     */
    public function get($id)
    {
        return $this->client->request(
            self::GET,
            Routes::plans()->details($id)
        );
    }
```

## Ambiente

* SDK Pagar.me v4

**Comment by devdrops** [comment]
Excelente pergunta, @leonampd!

Lembro que quando discutimos o uso de arrays, optamos por usar dessa forma para manter um padrão nos parâmetros - usar sempre um tipo de entrada, e consumí-la como um `destruct`.

Honestamente eu não vejo problemas nisso (passando um valor ou um array, o efeito é o mesmo). Poderia trazer mais detalhes pra gente aprofundar a discussão?

**Comment by leonampd** [comment]
@devdrops Acho que a semântica do código não fica legal. Dado como a API funciona - que usa somente o ID para a recuperação do dado, que não oferece outra maneira de fazer essa recuperação - eu como desenvolvedor ao ler a documentação da API e do SDK esperaria que o método `get` recebesse o ID como parâmetro e não um array chamado `$payload` inclusive.

Permitir um array como parâmetro, assim como os outros métodos, fica implícito que é possível informar algo além do ID, o que não é verdade. Por isso acredito que nestes casos o ideal seria mudar o contrato do método.

**Comment by piiih** [comment]
Então, mas ai depende do método, por exemplo, em transactions a gente pode utilizar o `reference_key` como um campo para fazer o get. E se não me engano outros endpoints também possuem outras opções de parâmetros que podem ser passado @leonampd .

**Comment by murilohns** [comment]
@piiih, acredito que você tenha entendido errado.

o `get` destes métodos está aceitando um `array` como parâmetro, mas no final das contas ele utiliza apenas o `id` desse `array`. Por exemplo:

```php
$pagarme->transactions()->get([
    'id' => '1234';
])
```

Irá bater no _endpoint_ `api.pagar.me/1/transactions/1234`. Todos os outros parâmetros, se passados no `array`, serão ignorados.


A sugestão do @leonampd é alterar a assinatura desse método para aceitar apenas o ID como parâmetro. Ficaria assim:

```php
$pagarme->transactions()->get('1234')
```

O que daria no mesmo resultado que o exemplo anterior, mas mudando a assinatura do método.
