### ISSUE TITLE
boleto_url errado na v1.1.0

### ISSUE THREAD

**Issue by cassianotartari** [pagarme/pagarme-php#311]
## Contexto

Possuímos uma plataforma de ecommerce SaaS e nossa integração está funcionando porém recentemente vocês começaram a enviar a ``boleto_url`` errada. Temos integração com vários gateways.

## Ambiente
* SDK Pagar.me v1.1.0
* Servidor Linux Debian 8
* PHP 5.6.38
* Nginx 1.12.1

## Passos para reproduzir

Crie uma transação utilizando boleto bancário.

## Resultado esperado

Que a response venha com o ``boleto_url`` com a url correta para emissão do boleto. 

## Resultado atual

Atualmente vocês estão retornando ``https:\/\/pagar.me``

## Response exemplo retornada por vocês:
```json
{
    "object": "transaction",
    "status": "waiting_payment",
    "refuse_reason": null,
    "status_reason": "acquirer",
    "acquirer_response_code": null,
    "acquirer_name": "pagarme",
    "acquirer_id": "5ae087fea32ca81736f31e41",
    "authorization_code": null,
    "soft_descriptor": "1809772911",
    "tid": 4311685,
    "nsu": 4311685,
    "date_created": "2018-09-25T18:39:12.704Z",
    "date_updated": "2018-09-25T18:39:13.280Z",
    "amount": 13524,
    "authorized_amount": 13524,
    "paid_amount": 0,
    "refunded_amount": 0,
    "installments": 1,
    "id": 4311685,
    "cost": 0,
    "card_holder_name": null,
    "card_last_digits": null,
    "card_first_digits": null,
    "card_brand": null,
    "card_pin_mode": null,
    "postback_url": "<omitido>",
    "payment_method": "boleto",
    "capture_method": "ecommerce",
    "antifraud_score": null,
    "boleto_url": "https:\/\/pagar.me",
    "boleto_barcode": "1234 5678",
    "boleto_expiration_date": "2018-09-29T03:00:00.000Z",
    "referer": "api_key",
    "ip": "54.172.169.208",
    "subscription_id": null,
    "phone": {
        "object": "phone",
        "ddi": "55",
        "ddd": "048",
        "number": "84045954",
        "id": 363050
    },
    "address": {
        "object": "address",
        "street": "Rua Teste SP",
        "complementary": "03",
        "street_number": "1",
        "neighborhood": "centro",
        "city": "Sumar\u00e9",
        "state": "SP",
        "zipcode": "13181781",
        "country": "Brasil",
        "id": 485281
    },
    "customer": {
        "object": "customer",
        "id": 745729,
        "external_id": null,
        "type": null,
        "country": null,
        "document_number": "<omitido>",
        "document_type": "cpf",
        "name": "<omitido>",
        "email": "<omitido>",
        "phone_numbers": null,
        "born_at": "1988-03-28T00:00:00.000Z",
        "birthday": null,
        "gender": "F",
        "date_created": "2018-09-25T18:39:12.515Z",
        "documents": []
    },
    "billing": null,
    "shipping": null,
    "items": [],
    "card": null,
    "split_rules": null,
    "metadata": {
        "pedido": {
            "number": "1809772911"
        }
    },
    "antifraud_metadata": [],
    "reference_key": null,
    "device": null,
    "local_transaction_id": null,
    "local_time": null,
    "fraud_covered": false,
    "order_id": null,
    "risk_level": "unknown",
    "receipt_url": null,
    "payment": null,
    "addition": null,
    "discount": null
}
```

**Comment by murilohns** [comment]
fala @cassianotartari , você está utilizando a chave de testes nessa integração, por isso a URL do boleto está sendo retornada dessa maneira.

Por favor, altere sua chave de API para a de ambiente live, ela tem o prefixo _ak_live_.

Você pode encontrá-la acessando esse [link](https://dashboard.pagar.me/#/myaccount/apikeys).

**Comment by cassianotartari** [comment]
Valeu @murilohns pela rápida resposta, vim correndo aqui pra tentar apagar a issue porque vi que outro cliente tinha conseguido gerar a url corretamente.

Não participei do desenvolvimento dessa integração e desconhecia esse comportamento, acabei de descobri lendo o FAQ ([[1](https://pagarme.zendesk.com/hc/pt-br/articles/206293813-Como-fa%C3%A7o-para-abrir-um-boleto-rec%C3%A9m-gerado-no-navegador-)], [[2](https://pagarme.zendesk.com/hc/pt-br/articles/205967636-Posso-gerar-um-boleto-em-modo-teste-)]). Até peço desculpas por ter aberto esse tópico sem pesquisar melhor. Talvez valha a menção sobre esse comportamento [nessa sessão](https://docs.pagar.me/v2013-03-01/docs/realizando-uma-transacao-de-boleto-bancario#section-status-da-transa%C3%A7%C3%A3o) da documentação.

Muito obrigado!
