### ISSUE TITLE
Falta de clareza nas mensagens de Exception

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-php#317]
## Contexto

A nova versão do SDK (v4) possui uma exception `PagarMe\Exceptions\PagarMeException` que tem o objetivo de abstrair as mensagens de erro que são enviadas pela API do Pagar.me nas respostas de requests. Ela contempla, em sua maioria o seguinte formato:

```json
{
    errors: [
        {
            message: "value" must be an array",
            parameter: "items",
            type: "InvalidType
        }
    ]
}
```

O problema em questão é que, atualmente o SDK só retorna `"value must be an array` e todo o restante da informação precisa ser consultado invocando outros métodos que não o _"default"_ _getMessage_ de uma exception da linguagem.

## Ambiente

* SDK Pagar.me v4.0.0-alpha
* Servidor Linux
* PHP 7.2

## Passos para reproduzir

1. instancie um objeto `PagarMe\Client` informando uma _api key_ válida.
2. invoque o método de crianção de transação informando um payload inválido envolvendo-o em um bloco de _try/catch_ sendo que no _catch_ deve ser instanciado um objeto `PagarMe\Exceptions\PagarMeException`
3. No bloco _catch_ invoque somente o método _getMessage()_ da exception.

## Resultado esperado

Os atributos enviados no response da API (_type_, _parameter_ e _message_) devem estar presentes na mensagem de erro tornando-a mais clara.

## Resultado atual

Somente o atributo _message_ é mostrado.

## Possível correção

Buildar a mensagem de forma que ela contenha as infos desejadas

## Screenshots

![image](https://user-images.githubusercontent.com/1620107/48012186-91636b80-e108-11e8-8f5b-76e548e9838b.png)

**Comment by tkzaum10** [comment]
@leonampd Interessante o seu comentário aparentemente esse feature está parado a algum tempo. Não seria interessante passar também o código do status http junto com a response com um ->getCode();

Ficaria mais simples para fazer o handle do erro.

Grato

**Comment by leonampd** [comment]
@tkzaum10 Acho que faz sentido sim inserir o statusCode. Essa demanda vai ser feita mas precisamos atacar outras frentes que são mais prioritárias. Em todo caso, se quiser abrir um Pull Request que ajusta isso, ficaremos muito felizes em revisar! :wink:

**Comment by diogomachado** [comment]
Também estou com essa dúvida, por exemplo, quando tento capturar o erro passando valores incorretos, como um CPF inválido, eu não consigo capturar todos os campos de erro do Pagarme, isso foi corrigido?

**Comment by leonampd** [comment]
Opa! Td bem @diogomachado? Por enquanto ainda não temos uma forma de exibir todos os erros retornadas da nossa API. Tem alguma sugestão?

**Comment by diogomachado** [comment]
Oi @leonampd, uma coisa que me ajudou aqui foi criar um método que retorna a _errorMessage_ no PagarMeException.php:

```
/**
   * @return string
   */
public function getErrorMessage()
{
    return $this->errorMessage;
}
```

Com isso eu consigo saber o que está faltando na chamada, será que vale um pull request?

**Comment by leonampd** [comment]
@diogomachado nesse caso você nem precisa criar um novo método. Basta chamar o método _default_ `getMessage()`. Porém, pra obter a lista de erros que a API retorna nosso SDK ainda não tem algo pra isso. Vamos pensar em uma forma razoável de atender essa necessidade.

**Comment by diogomachado** [comment]
@leonampd, não existe esse método dentro do PagarMeException

**Comment by leonampd** [comment]
@diogomachado tem sim. `PagarMeException` extende `Exception` que é a classe default da linguagem. Veja:

https://github.com/pagarme/pagarme-php/blob/f7f9a5f9bfe8d255ca306c7ae9dde4101ad59152/src/Exceptions/PagarMeException.php#L5
