### ISSUE TITLE
Adicionando a Classe para trabalhar com a Pesquisa

### ISSUE THREAD

**Issue by mariovalney** [pagarme/pagarme-php#32]
Não há classe para trabalhar com o endpoint Search.

Criei a classe e o método **search()**, que recebe o $type, $query e $search_type de acordo com a documentação. Além dele, o método **searchTransactionByMetadata()** para pesquisar metadados em transações.

**Comment by mariovalney** [comment]
PR: #31

**Comment by ricardotulio** [comment]
The #V2 has been deprecated since the release of V3 and this issue will be resolved in the #V3.
