### ISSUE TITLE
Revisão README

### ISSUE THREAD

**Issue by horphoz** [pagarme/pagarme-php#322]
Na parte dos Postbacks os exemplos são inválidos para o SDK na versão atual.

Exemplo Incorreto:  $pagarMe->postbacks()->validate($payload, $signature);
Exemplo Funcional: $pagarMe->postback()->validateRequest($payload, $signature);

**Comment by murilohns** [comment]
Olá @horphoz, o código `$pagarMe->postbacks()->validate($payload, $signature);` é válido para a versão 4.x do SDK, enquanto este: `$pagarMe->postback()->validateRequest($payload, $signature);` é válido para a versão 3.x do SDK.

Por favor, veja qual versão você tem instalada em seu sistema, e verifique em qual branch você está consultando o README =)

Qualquer dúvida fico à disposição.
