### ISSUE TITLE
Como imprimir array de resposta da API pagar.me

### ISSUE THREAD

**Issue by anacaroline-it9** [pagarme/pagarme-php#324]
Estou com problemas pra imprimir o array de resposta da API.
Estou inserindo minha chave certa, quando coloco a variável $balanceOperation em um var_dump,ele me mostra os resultados que preciso, mas se tento imprimir um determinado item dessa forma 'echo $balance["id"];' ou dessa forma 'echo $balance[0];', não aparece as informação.

a pergunta é: COMO EU IMPRIMO ESTE ARRAY???????????

TENTATIVA FALHA:
```php
<?php
header('Content-Type: application/json; charset=utf-8');  
require('vendor/autoload.php');
$pagarme = new PagarMe\Client('minhachave');

$balanceOperations = $pagarme->balanceOperations()->getList();
var_dump($balanceOperations);

$balance=  json_encode($balanceOperations);
echo $balance["id"];
?>
```

**Comment by murilohns** [comment]
Olá @anacaroline-it9, tente utilizar `$balance->id`

**Comment by anacaroline-it9** [comment]
> Olá @ anacaroline-it9 , tente utilizar:
> 
> ```
> $ balanceOperations  =  $ pagarme -> balanceOperations () -> getList ();
> 
> foreach ( $ balanceOperations  como  $ balanceOperation ) { 
> echo $ balanceOperation -> id ; }     
> ```

Obrigada salvou minha vida!!!!
