### ISSUE TITLE
como exibir todas as transações

### ISSUE THREAD

**Issue by anacaroline-it9** [pagarme/pagarme-php#326]
estou usando a api com API, gostaria de saber como exibir todas as transações, pois só aparece 10 por vez, segue o código:

<?php
require('vendor/autoload.php');
$pagarme = new PagarMe\Client('000');
$paidTransactions = $pagarme->transactions()->getList();
      foreach($paidTransactions as $paidTransactions) {
	   $idtransacaoTran = $paidTransactions->id;
      }
?>

**Comment by leonampd** [comment]
Oi @anacaroline-it9 tudo bem?

O retorno de `transactions()->getList()` é paginado. Para você iterar por todos os itens você pode usar os parâmetros `count` e `page` que a própria API informando-os no payload dessa forma, por exemplo:

```php
// code...

$pagarme->transactions()->getList([
	'count' => 20, // quantidades de itens que devem ser retornados
	'page' => 1, // pagina
])
```

**Comment by anacaroline-it9** [comment]
Obrigada, resolvido!
