### ISSUE TITLE
Retornar apenas transações com data maior que uma semana atrás

### ISSUE THREAD

**Issue by anacarolinelisboa** [pagarme/pagarme-php#329]
Estou tendo problemas com data, preciso recuperar apenas transações com data maior que sete dias atrás, segue o código:

$pagarme = new PagarMe\Client('MINHA CHAVE');
$paidTransactions = $pagarme->transactions()->getList([
	'count' =>99999,
	'page' => 1,
]);

**Comment by anacarolinelisboa** [comment]
Como fazer quando é preciso coolocar uma variável? do jeito abaixo não funciona:

$t=time();
$menos7dias = strtotime("-7 days", $t); 

$pagarme = new PagarMe\Client('MINHA CHAVE');
$paidTransactions = $pagarme->transactions()->getList([
	'count' => 99999,
       'page' => 1,
       'date_created' => '>=$menos7dias'
]);

**Comment by leonampd** [comment]
Oi @anacarolinelisboa,

Bom, nesse caso não funcionou pois em em `date_created` vc colocou aspas simples `'`. Aspas simples, no PHP é interpretado com string literal, ou seja o php não interpretou o valor da var `$menos7dias` e sim usou como se fosse um texto `>=$menos7dias`.

Pra resolver isso você pode simplesmente usar aspas duplas `"`.

**Comment by anacarolinelisboa** [comment]
Oi Leo, mesmo com aspas duplas ele continua pegando transações com data fora desse periodo:
$t=time();
$menos7dias = strtotime("-7 days", $t); 

$pagarme = new PagarMe\Client('MINHA CHAVE');
$paidTransactions = $pagarme->transactions()->getList([
'count' => 999,
    'page' => 1,
    'date_created' => ">=$menos7dias"
]);

**Comment by anacarolinelisboa** [comment]
?

**Comment by leonampd** [comment]
oi @anacarolinelisboa desculpa a demora em responder. Bom isso é bem estranho. Manda um e-mail pro suporte@pagar.me, pfv? O time vai conseguir ver no detalhe o que pode estar ocorrendo na sua conta, tudo bem?

**Comment by hfoletto** [comment]
Olá, @anacarolinelisboa e @leonampd , tudo bem?
Estava buscando por essa funcionalidade e encontrei esse issue aqui, eu testei os códigos e percebi que retorna as transações, porém o argumento `date_created` não é respeitado, mas sim o `count`.

Uma outra peculiaridade que percebi foi ao usar os operadores `<=` e `<`, ambos sempre retornaram um array vazio.

Realizei testes tanto em ambiente de teste como em produção.

Há alguma novidade a respeito disso?

**Comment by anacarolinelisboa** [comment]
Olá @hfoletto !!
Entrei em contato e a solução que tive para o meu problema em buscar data maior que foi:

$t=time();
$menos10dias = strtotime("-10 days", $t); 

$pagarme = new PagarMe\Client('MINHA-CHAVE');
$paidTransactions = $pagarme->transactions()->getList([
	'count' => 99999,
    'page' => 1,    
    'date_created' => '>='.$menos10dias.'000',
]);

**Comment by hfoletto** [comment]
@anacarolinelisboa , obrigado pela resposta!

Testei aqui, e funcionou conforme o esperado! Então o formato de tempo que eles estão usando é em milissegundos, não segundos, como é o padrão do php e a convenção em muitos lugares, por isso os 3 zeros no final. 

Acredito que seria interessante colocar isso na documentação, visto que o comentário cita apenas que deve ser unixTimeStamp.

**Comment by leonampd** [comment]
Show de bola pessoal. @anacarolinelisboa fico feliz que o time conseguiu te ajudar a resolver o problema. @hfoletto vou abrir uma issue pra trackearmos o seu feedback e adicionar na documentação. Vlw!
