### ISSUE TITLE
status do pagamento

### ISSUE THREAD

**Issue by brasildevandroid** [pagarme/pagarme-php#334]
estou fazendo uma chamada para um back end php através de uma aplicaçao android no qual realiza á transação de pagamento como no github,faz o processo e o pagamento é aprovado até ai tudo blz,o problema é que eu não sei como retornar uma resposta do status de pagamento,eu precisava que logo depois de ter processado á transação ele me desse um retorno mais não sei como fazer isso vocês podem me ajudar,obrigado!

**Comment by leonampd** [comment]
Oi @brasildevandroid tudo bom?

Não sei se entendi bem sua pergunta mas pelo que entendi você precisa retornar o status da transação na resposta da requisição, certo? Bom, para você recuperar o status da transação é simples:

**Criando a transação:**
```php
$transaction = $pagarme->transactions()->create([
    'amount' => 1000,
    'payment_method' => 'credit_card',
    'card_holder_name' => 'Anakin Skywalker',
    'card_cvv' => '123',
    'card_number' => '4242424242424242',
    'card_expiration_date' => '1220',
    'customer' => [
        'external_id' => '1',
        'name' => 'Nome do cliente',
        'type' => 'individual',
        'country' => 'br',
        'documents' => [
          [
            'type' => 'cpf',
            'number' => '00000000000'
          ]
        ],
        'phone_numbers' => [ '+551199999999' ],
        'email' => 'cliente@email.com'
    ],
    ...
]);
```

**Obtendo o status**
```php
echo $transaction->status; // 123456
```

Agora, como você vai externalizar esse status não faz parte do escopo do sdk e vai depender de como sua aplicação está desenvolvida. Vou deixar abaixo 2 links que podem servir de ponto de partida caso vc esteja usando algum framework:

- symfony: https://symfony.com/doc/current/components/http_foundation.html#creating-a-json-response
- laravel: https://laravel.com/docs/5.8/responses#json-responses

Espero ter conseguido ajudar 😉
