### ISSUE TITLE
Erro: Número do documento faltando

### ISSUE THREAD

**Issue by ludioao** [pagarme/pagarme-php#335]
## Contexto
Pessoal, estou com um problema na minha aplicação, parou de funcionar do nada. 
O Pagar.me retorna o seguinte erro: 
![image](https://user-images.githubusercontent.com/7070404/60059152-4dce6980-96b9-11e9-89ea-c503a27568bc.png)

Estou utilizando o 
$pagarme->transactions()->create() - com os seguintes argumentos:
![image (3)](https://user-images.githubusercontent.com/7070404/60059163-5cb51c00-96b9-11e9-89c0-9b9874bb2a80.png)

## Ambiente
* pagarme/pagarme-php 4.0,
* Servidor Linux
* PHP 7.1
* Apache 2.2
* MySQL 5.6
* Laravel 5.6

**Comment by murilohns** [comment]
Olá @ludioao, acredito que a versão de API que está configurada em sua conta é a `2017-07-17`, ou a `2013-03-01`. Nesse caso, o payload que deve ser enviado no objeto `customer` fica assim:

```php
...
"customer" => array(
    "name" => "Nome cliente",
    "document_number" => "11111111111",
    "email" => "mail@mail.com",
    "address" => array (
        "street" => "rua",
        "street_number" => "123",
        "neighborhood" => "bairro",
        "city" => "cidade",
        "state" => "sp",
    ),
    "phone" => array (
        "ddd" => "11",
        "number" => "912345678",
    )
)
...
```

**Comment by ludioao** [comment]
É, era exatamente isso @murilohns . A cliente integrou com a Loja Integrada, e o suporte da plataforma lá alterou a API e ela não me informou.

Muito obrigado!
