### ISSUE TITLE
[Pergunta] status V4 vs V3

### ISSUE THREAD

**Issue by douggr** [pagarme/pagarme-php#336]
## Contexto

Estamos finalmente migrando da versão 1.x para latest, minha dúvida é: qual a versao estável / aconselhada?

Nas releases indica 3.x como ultima versão, mas 4.x ja foi taggeado tambem.

Obrigado.

**Comment by murilohns** [comment]
@douggr, a V3 tem manutenções periódicas pois alguns projetos dependem dela.

Já a V4 é a mais recente, e possui mais feature para uso =]

Cabe à você escolher qual se adapta melhor ao seu projeto

**Comment by douggr** [comment]
Joia, muito obrigado!
