### ISSUE TITLE
Pergunta - como criar uma transação com os card e customer que já tenho na V4

### ISSUE THREAD

**Issue by adrianosmateus** [pagarme/pagarme-php#343]
## Contexto

Não achei em nenhum lugar da documentação uma explicação clara de como gerar uma transação na versão 4 do sdk usando os ids de um cartão e de um customer que eu já tenha previamente gerado. Como posso fazer isso?

**Comment by murilohns** [comment]
Olá @adrianosmateus, basta passar o id desses objetos no corpo da transação.

Por exemplo:

```php
$transaction = $pagarme->transactions()->create([
  "card_id" => "card_abc123",
  "customer_id" => "123456",
  "payment_method" => "credit_card",
  ...
])
```
