### ISSUE TITLE
[Problema] - ERROR TYPE: validation_error. PARAMETER: customer. MESSAGE: "value" is required

### ISSUE THREAD

**Issue by adrianosmateus** [pagarme/pagarme-php#344]
## Contexto

Estou implementando a plataforma conforme a documentação da versão 4, e no momento de criar uma transação, recebo um retorno de erro que não consigo entender o que pode estar causando

## Ambiente

* SDK Pagar.me 4.0.4
* Servidor Linux
* PHP 7.2
* Nginx 1.14
* MySQL 5.6
* Laravel framework

## Passos para reproduzir

Tentei gerar uma instância de uma transação usando uma estrutura semelhante a essa:
`{
    "amount": 1000,
    "card_id": "{{id do cartao aqui}}",
    "customer_id": {{id do cliente aqui}},
    "payment_method": "credit_card",
    "billing": {
        "name": "Teste Nome da Silva",
        "address": {
            "country": "br",
            "street": "R. Álvares Penteado",
            "street_number": "49",
            "state": "sp",
            "city": "São Paulo",
            "neighborhood": "Centro Histórico de São Paulo",
            "zipcode": "01012001"
        }
    },
    "items": [
        {
            "id": "1",
            "title": "teste",
            "unit_price": 1000,
            "quantity": 1,
            "tangible": true
        }
    ]
}`

## Resultado esperado

Uma instância de uma transação.

## Resultado atual

Mensagem de erro "ERROR TYPE: validation_error. PARAMETER: customer. MESSAGE: "value" is required"

## Screenshots

![Captura de tela de 2019-08-09 16-24-46](https://user-images.githubusercontent.com/14916799/62804006-5b517e80-bac2-11e9-9ab6-8a02017501a3.png)

**Comment by adrianosmateus** [comment]
Fiz umas mudanças e percebi que o problema está em usar o "customer_id" sem ter o "customer". Colocando os dados do cliente direto na função sem usar o "customer_id" funciona normalmente. Talvez isso seja algum erro do SDK que está apresentando problema quando tentamos gerar uma transação usando apenas o id do customer previamente criado.

**Comment by leonampd** [comment]
Oi @adrianosmateus tudo bem? Na verdade o erro acontecia pq, segundo o print, vc não estava enviando o campo `customer` e `customer_id` não é um campo válido no contrato da API.

**Dica:** essa nova versão do sdk foi pensada de forma que quem a use, possa simplesmente definir o payload dos requests informando um array como parâmetro pros métodos (que representam os endpoints e verbos HTTP). Significa que você pode (e deve) fazer uso de toda a documentação oficial do pagar.me que fica nesse link: 

https://docs.pagar.me/reference
