### ISSUE TITLE
Composer desatualizado

### ISSUE THREAD

**Issue by assisjeferson** [pagarme/pagarme-php#35]
Estou utilizando a lib pelo composer e a versão esta desatualizada.

**V1.1.0** - 2015-11-13 16:08 UTC

Nessa versão não tem o método `validateRequestSignature`, provavelmente muitas outras melhorias pois tem vários commits a partir dessa data.

A versão dev-master esta atualizada, porém como esta em desenvolvimento pode esta instável.

**Comment by mathop** [comment]
+1

**Comment by mathop** [comment]
Ping @pedrofranceschi

**Comment by pplanel** [comment]
+1 né?

**Comment by mmlo** [comment]
Alguma novidade?

**Comment by fndmiranda** [comment]
+1

**Comment by raphagodoi** [comment]
+1

Alguém esta usando?

Estou implementando agora a biblioteca junto com Laravel 5.2.

Não queria partir pra usar CURL ou Ruby, é gambiarra d+

**Comment by Azakur4** [comment]
ahah pois se não quiser usar o CURL não use a lib kkkk já que a mesma usa o curl pra fazer as requisições :P

Mas entendo o que vc queria dizer usar a lib fica mais limpo se usar com composer e deixando a responsabilidade da manutenção com o povo do pagar.me

**Comment by ricardotulio** [comment]
Fala pessoal, tudo bem?

Estou fechando essa issue porque este problema já foi solucionado, como podem conferir no packagist https://packagist.org/packages/pagarme/pagarme-php.
