### ISSUE TITLE
Como faço para recuperar todas as transações cujo email do cliente seja X?

### ISSUE THREAD

**Issue by pedrofurtado** [pagarme/pagarme-php#350]
@leonampd @devdrops  Hoje para recuperar todas as assinaturas, com paginação, fazemos algo assim:

```php
$pagarMe->subscription()->getList($page, $count)
```

como adicionar filtros de por ex, email do cliente igual a X nessa lista? para filtrar no caso.

**Comment by leonampd** [comment]
Fala @pedrofurtado tudo bem?

Os filtros disponíveis são os que a API disponibiliza, você pode ver quais são [aqui](https://docs.pagar.me/reference#retornando-uma-assinatura). O filtro por e-mail não é um deles =/

**Comment by pedrofurtado** [comment]
@leonampd Obrigado pelo feedback!
