### ISSUE TITLE
Problemas para criar transação

### ISSUE THREAD

**Issue by anacarolinelisboa** [pagarme/pagarme-php#351]
Estou tendo problemas ao criar uma transação. aparece : "Esta página não está funcionando".
Será um problema com a variável?

$pagarme = new PagarMe\Client('minhaChave');
$transaction = $pagarme->transactions()->create([
// $transaction = ([
  'amount' => $valor,
  'payment_method' => 'credit_card',
  'card_holder_name' => 'Anakin Skywalker',
  'card_cvv' => '123',
  'card_number' => '4242424242424242',
  'card_expiration_date' => '1220', 
  'async' => false,
  'customer' => [
	'external_id' => '$idpagarme',
	'document_number' => '$cpfIN',
	'document_type' => 'cpf',
	'name' => '$nomeIN',
	'email' => '$emailIN',
		'address' => [
		    'street' => '$enderecoIN', 
		    'complementary' => '$complementoIN',
		    'street_number' => '$numeroIN',
		    'neighborhood' => '$bairroIN',
		    'zipcode' => '$cepIN'
		],
	'phone_numbers' => [ '+551199999999' ] 
   ],
	'metadata' => [
		'idProduto' => $idplan,
		'turma' => '4832'
	]
]);

**Comment by murilohns** [comment]
Oi @anacarolinelisboa, tudo bem? =]

Esse erro não é característico da API do Pagar.me.

Você pode colocar esse código em um `try/catch` e capturar o erro que de fato está sendo gerado, assim conseguimos investigar melhor o problema =]
