### ISSUE TITLE
Impossibilidade de criar pagamento de cartão de crédito via API

### ISSUE THREAD

**Issue by fpviviani** [pagarme/pagarme-php#363]
Quando tento criar um pagamento do tipo cartão de crédito, ao criar a transação recebo a seguinte mensagem de erro:
    "message": "ERROR TYPE: invalid_parameter. PARAMETER: pan. MESSAGE: Formato inválido.",
    "status_code": 500,

Conferi coma documentação e todos os parâmetros necessários estão sendo passados, no formato correto. Estou tentando via Postman. 

## Ambiente
Objeto que estou enviando ao criar a transação:
array:10 [
  "amount" => 50
  "payment_method" => "credit_card"
  "card_holder_name" => "Fabio"
  "card_cvv" => "123"
  "card_number" => "5555555"
  "card_expiration_date" => "1221"
  "customer" => array:7 [
    "name" => "Fabio Piovani"
    "type" => "individual"
    "country" => "br"
    "documents" => array:1 [
      0 => array:2 [
        "type" => "cpf"
        "number" => "222222"
      ]
    ]
    "phone_numbers" => array:1 [
      0 => "+5511999609839"
    ]
    "email" => "email@email"
    "external_id" => "12"
  ]
  "billing" => array:2 [
    "name" => "aaaaaaa"
    "address" => array:7 [
      "country" => "br"
      "street" => "aa"
      "street_number" => "2"
      "state" => "mg"
      "city" => "itajubá"
      "neighborhood" => "a"
      "zipcode" => "37500206"
    ]
  ]
  "items" => array:1 [
    0 => array:5 [
      "id" => "1"
      "title" => "mensalidade"
      "unit_price" => 50
      "quantity" => "1"
      "tangible" => false
    ]
  ]
  "postback_url" => "https://xxxxx/finances/postback"
]

**Comment by murilohns** [comment]
@fpviviani, esse problema ainda está acontecendo? Ou conseguiu resolver?

**Comment by fpviviani** [comment]
> @fpviviani, esse problema ainda está acontecendo? Ou conseguiu resolver?

Ainda está :c

**Comment by fpviviani** [comment]
Atualização: Parâmetro PAN se trata do número do cartão. Para dar certo em ambiente de testes, tem que ter exatamente 16 dígitos, menos ou mais quebra o formato. Fica a dica pra quem passar por isso.
Vou fechar a issue.
