### ISSUE TITLE
Tentativa de criar Pagamento com document CNPJ retorna que deve ser CPF

### ISSUE THREAD

**Issue by xande-ibtech** [pagarme/pagarme-php#364]
Implementação própria da V3 da API

Ao tentar criar uma transação de um cliente CNPJ estou recebendo a seguinte mensagem de erro

[type] => validation_error
[parameter_name] => customer
[message] => The documents field must contain a document of type CPF

Sendo que na API estou passando o documento do tipo CNPJ

    [customer] => Customer Object
        (
            [external_id] => 1718
            [name] => FAKINI MALHAS LTDA
            [type] => individual
            [country] => br
            [email] => matheus@ibtech.inf.br
            [documents] => Array
                (
                    [0] => Document Object
                        (
                            [type] => cnpj
                            [number] => 05082188000188
                        )

                )

Talvez algo relacionado ao type do customer ?
Procurei na documentação e não encontrei nada especificando esse item para cnpjs

Poderiam dar uma Luz ?

**Comment by fpviviani** [comment]
Não tenho 100% certeza, mas acredito que seja o "type". "individual" provavelmente requer um cpf como documento. Tenta pesquisar os outros "types" que são aceitos

**Comment by xande-ibtech** [comment]
Opa era isso mesmo, o customer type tem que vir como "corporation" achei aqui
https://docs.pagar.me/reference#criando-um-cliente

Obrigado!
