### ISSUE TITLE
$options['headers'] substituídos na chama do addUserAgentHeaders()

### ISSUE THREAD

**Issue by fernando-rosa** [pagarme/pagarme-php#366]
## Contexto

Quando criamos um Cliente, como no exemplo abaixo:
```
$api_key = '***************';
$extras = ['headers' => ['X-Pagarme-Version' => '2013-03-01']];
$client = new Client($api_key, $extras);
```
Nosso 'headers' é substituído pelos valores retornados pela função addUserAgentHeaders(), como podemos verificar o código do Client.php (linha 153):

`$options['headers'] = $this->addUserAgentHeaders($userAgent);`

## Ambiente

* SDK Pagar.me v4.1.0

## Passos para reproduzir

Criar um cliente como o exemplo abaixo e verificar via bebug que os valores do $extras['headers'] são perdidos:

```
$api_key = '***************';
$extras = ['headers' => ['X-Pagarme-Version' => '2013-03-01']];
$client = new Client($api_key, $extras);
```

## Resultado esperado

Esperamos que $extras['headers'] seja mantido no $options['headers'] na linha 155 do Client.php.

## Resultado atual

$options['headers'] na linha 155 tem apenas os valores retornados pela função addUserAgentHeaders. Todos os outros definidos previamente são perdidos.

## Possível correção

Efetuar o merge dos headers passados com os retornados pela função addUserAgentHeaders, como no código abaixo:

```
$headers = isset($options['headers']) ?
    $options['headers'] :
    [];

$options['headers'] = array_merge($headers, $this->addUserAgentHeaders($userAgent));
```

**Comment by murilohns** [comment]
Corrigido no #367
