### ISSUE TITLE
[Dúvida] Cobrando com Pix

### ISSUE THREAD

**Issue by silasrm** [pagarme/pagarme-php#393]
## Contexto

Preciso integrar cobrança usando Pix. E vendo a documentação (https://docs.pagar.me/reference#pix-2), tem o objeto "payments" dentro do objeto principal, que deve ser passado os dados. Mas hoje utilizo, para cartão de crédito, a estrutura de exemplo da biblioteca, que é passado os dados do cartão no objeto principal. 

## Questão

Basta eu remover os dados de cartão, do objeto principal, e usar a estrutura da documentação oficial para o Pix, e funcionará? 
Pergunto, pois, não achei na documentação a estrutura do exemplo da biblioteca, até o campo _card_expiration_date_ não encontrei citação a ele.

**Comment by thiagomorello** [comment]
Estou com a mesma dúvida, a documentação não deixa claro como devemos fazer para utilizar.

**Comment by silasrm** [comment]
Conseguiu alguma solução @thiagomorello ?

**Comment by silasrm** [comment]
Segue o que achei no PDF e deve funcionar com a API < 5:

![image](https://user-images.githubusercontent.com/197187/141810877-761e4646-765c-4ce2-9453-b8b4c982c7c1.png)
![image](https://user-images.githubusercontent.com/197187/141810904-6c8a95c7-1b9d-4fd8-a636-8da3c216a9b0.png)
![image](https://user-images.githubusercontent.com/197187/141810920-59a6f1ab-4769-48af-aed4-d43fb8adc5cc.png)
