### ISSUE TITLE
Versão que esta em master não esta criando cartão de crédito

### ISSUE THREAD

**Issue by raphagodoi** [pagarme/pagarme-php#53]
Estou recebendo um erro 500 no arquivo Request.php ao tentar criar um cartão.

Esta é a versão certa.. pois tentei usar a libv2.. e funcionou.. porém não esta disponivel ainda os metodos para planos e assinaturas.

**Comment by xduh** [comment]
Olá @raphagodoi, por favor, revise se a implementação está de acordo com a doc (https://docs.pagar.me/api/?php#criando-um-cartao), caso persista forneça mais detalhes sobre sua implementação.
Não utilize o branch libv2, pois está em desenvolvimento e ainda não há garantia da interface.
