### ISSUE TITLE
Atualização de Plano não funciona

### ISSUE THREAD

**Issue by luisrock** [pagarme/pagarme-php#80]
Embora a funcionalidade esteja OK via cURL, não está funcionando através do código PHP indicado na documentação, que faz uso dessa biblioteca:

```
require("pagarme-php/Pagarme.php");

    Pagarme::setApiKey("ak_test_grXijQ4GicOa2BLGZrDRTR5qNQxJW0");

    $plan = PagarMe_Plan::findById("12785");

    $plan->setName("plano silver");
```

A resposta é válida, mas o nome não é alterado.

**Comment by devdrops** [comment]
Olá @luisrock! Essa versão do nosso SDK está depreciada, portanto sugiro utilizar uma das versões mais recentes.

Contudo, no seu caso, experimente utilizar o método `save` para persistir alterações em seus planos, conforme abaixo:

```php
PagarMe::setApiKey('ak_test_grXijQ4GicOa2BLGZrDRTR5qNQxJW0');

$plan = PagarMe_Plan::findById(12785);

$plan->setName('My New Name');
$plan->save();
```
